(function(){
'use strict';
const C=document.getElementById('game'),X=C.getContext('2d'),MC=document.getElementById('map'),MX=MC.getContext('2d'),MMC=document.getElementById('minimap'),MMX=MMC.getContext('2d');X.imageSmoothingEnabled=false;MX.imageSmoothingEnabled=false;MMX.imageSmoothingEnabled=false;
const W=C.width,H=C.height,T=32,WW=220,WH=130,A=window.GameAudio,$=id=>document.getElementById(id);
const ART={props:new Image(),arin:new Image()};ART.props.src='assets/world-v3/folklore-props-atlas.png';ART.arin.src='assets/world-v3/arin-atlas.png';
const ui={toast:$('toast'),prompt:$('prompt'),pin:$('pinText'),dialogue:$('dialogue'),speaker:$('speaker'),text:$('dialogueText'),portrait:$('portrait'),map:$('mapOverlay'),hp:$('hpBar'),hpText:$('hpText'),xp:$('xpBar'),xpText:$('xpText'),level:$('level'),coins:$('coins'),inventory:$('inventory'),detail:$('itemDetail'),skills:$('skillList'),qTitle:$('questTitle'),qText:$('questText'),objectives:$('objectives'),location:$('location'),compass:$('compass'),track:$('trackName'),clock:$('worldClock'),death:$('death'),questReward:$('questReward'),rewardTitle:$('rewardTitle'),rewardText:$('rewardText')};
const keys={},resources=[],enemies=[],loot=[],particles=[],floaters=[],fireflies=[],clouds=[];let state,player,last=performance.now(),time=0,saveClock=0,camera={x:0,y:0},shake=0,dialogue=null,target=null,toastTimer,selectedItem=null,mapOpen=false,currentRegion='village',weather='sunny',weatherUntil=28,menuOpen=true;
const items={axe:{icon:'🪓',name:'Jelševa sekira',desc:'Dobro uravnotežena sekira za navaden les.',rare:1},sword:{icon:'⚔️',name:'Bronasti meč',desc:'Osnovno orožje. Zahteva 1. raven.',rare:1,weapon:1,level:1},ironSword:{icon:'†',name:'Železni meč',desc:'Čvrsto železo. Zahteva 2. raven.',rare:1,weapon:3,level:2},steelSword:{icon:'†',name:'Jekleni meč',desc:'Ostro kaljeno jeklo. Zahteva 4. raven.',rare:1,weapon:4,level:4},blackSword:{icon:'†',name:'Črno rezilo Velesa',desc:'Temno rezilo iz globin. Zahteva 6. raven.',rare:1,weapon:6,level:6},mithrilSword:{icon:'†',name:'Mitrilni meč',desc:'Lahek kot list, trd kot skala. Zahteva 8. raven.',rare:1,weapon:8,level:8},adamantSword:{icon:'†',name:'Adamantni meč',desc:'Orožje gorskih knezov. Zahteva 10. raven.',rare:1,weapon:10,level:10},runeSword:{icon:'†',name:'Perunovo runsko rezilo',desc:'V njem poka grom. Zahteva 12. raven.',rare:1,weapon:12,level:12},dragonSword:{icon:'⚔',name:'Zmajski meč Zlatoroga',desc:'Legendarno rezilo kraljestva pod Triglavom. Zahteva 15. raven.',rare:1,weapon:15,level:15},pick:{icon:'⛏️',name:'Rudarski kramp',desc:'Razbije tudi trdo modro skalo.',rare:1},wood:{icon:'▰',name:'Jelšev les',desc:'Dišeč les iz starega gozda.'},mushroom:{icon:'🍄',name:'Žerjavna goba',desc:'Povrne 35 življenja. Bližnjica: tipka 1.',use:true},berry:{icon:'●●',name:'Mrakova jagoda',desc:'Temno modra jagoda za barvila.'},flower:{icon:'✿',name:'Mesečnica',desc:'Vilinska cvetlica, ki se odpre pod zvezdami.'},ore:{icon:'◆',name:'Modra ruda',desc:'Redka ruda iz vznožja Sivih zob.'},coin:{icon:'●',name:'Bakrenec',desc:'Trgovci jih štejejo tudi ob koncu sveta.'},banner:{icon:'⚑',name:'Prazno goblinsko praporje',desc:'Barva, ki ne pripada nikomur.',rare:1},scrap:{icon:'▧',name:'Goblinska zaponka',desc:'Kriva, cenena in presenetljivo uporabna.'},bell:{icon:'♢',name:'Zlatorogov zvonček',desc:'Srebrn zvonček odpre poti, ki jih oči ne vidijo.',rare:1},thunderRune:{icon:'ϟ',name:'Perunova runa',desc:'Topla runa, v kateri odmeva nevihta.',rare:1},waterPearl:{icon:'◉',name:'Biser Povodnega moža',desc:'Dokaz miru med reko in ljudmi.',rare:1}};
Object.assign(items,{bones:{icon:'🦴',name:'Kosti',desc:'Ostanki premaganega bitja. Pokoplji jih za duhovne EXP.',use:true},bread:{icon:'🍞',name:'Popotniški kruh',desc:'Povrne 22 življenja.',use:true,heal:22},hide:{icon:'▱',name:'Volčja koža',desc:'Material za lahko gozdno opravo.'},goblinVest:{icon:'♜',name:'Goblinski telovnik',desc:'Neroden, vendar ublaži nekaj škode.',armor:2},ironScimitar:{icon:'◒',name:'Železni krivec',desc:'Hiter ukrivljen meč po zgledu vzhodnih sablj. Zahteva 3. raven.',weapon:4,level:3,rare:1,scimitar:true},goldScimitar:{icon:'☾',name:'Zlati krivec kralja Samota',desc:'Starodavna zlata sablja iz Labirinta treh senc. Zahteva 7. raven.',weapon:9,level:7,rare:1,scimitar:true},sunShield:{icon:'◉',name:'Ščit treh sonc',desc:'Pozlačen ščit, ki zmanjša prejeto škodo.',armor:5,rare:1}});
const skillNames={woodcut:'Drvarjenje',forage:'Nabiralništvo',combat:'Bojevanje',mining:'Rudarjenje',spirit:'Izročilo',defence:'Obramba'};
const npcs=[{id:'mira',name:'Mira',x:15*T,y:49*T,body:'#735c8c',hair:'#d6c4a1'},{id:'iva',name:'Iva',x:22*T,y:53*T,body:'#456f78',hair:'#3a2b22'},{id:'grub',name:'General Grub',x:100*T,y:44*T,body:'#8d3e31',hair:'#3c3021',goblin:true},{id:'nib',name:'General Nib',x:119*T,y:57*T,body:'#435d8f',hair:'#30301f',goblin:true},{id:'lada',name:'Lada iz Belega gaja',x:169*T,y:35*T,body:'#82926a',hair:'#e2d8ac',elf:true},{id:'bor',name:'Kovač Bor',x:84*T,y:18*T,body:'#72533d',hair:'#b8a78f',dwarf:true},{id:'radovan',name:'Žrec Radovan',x:198*T,y:20*T,body:'#606d89',hair:'#ddd2bc'},{id:'miller',name:'Mlinar Jure',x:63*T,y:94*T,body:'#8a7450',hair:'#4a3526'}];
npcs.push(
  {id:'vid',name:'Stražar Vid',x:36*T,y:50*T,body:'#596557',hair:'#49372a',ambient:'Mestna vrata zapremo ob mraku. Ne zaradi volkov — zaradi davkarjev.'},
  {id:'neza',name:'Trgovka Neža',x:43*T,y:53*T,body:'#76584e',hair:'#c7a46f',ambient:'V Kresnikovem dobiš vse. Če česa ni, je verjetno prepovedano.'},
  {id:'rok',name:'Kovač Rok',x:49*T,y:47*T,body:'#66483c',hair:'#25211c',ambient:'Jeklo najprej posluša ogenj, potem kladivo in šele nazadnje bojevnika.'},
  {id:'ajda',name:'Ajda',x:51*T,y:56*T,body:'#65734f',hair:'#c5b18d',ambient:'Na tržnici pravijo, da se je v vodnjaku sinoči pokazal obraz Velesa.'},
  {id:'tine',name:'Pek Tine',x:39*T,y:58*T,body:'#877154',hair:'#60472e',ambient:'Topel hlebec zdravi skoraj vse. Za prekletstva potrebuješ dva.'},
  {id:'bojan',name:'Mestni pisar Bojan',x:46*T,y:61*T,body:'#4f6072',hair:'#8c7861',ambient:'Kresnikovo ima triindvajset zakonov o kozolcih in nobenega o zmajih.'},
  {id:'zala',name:'Zala',x:34*T,y:58*T,body:'#765f79',hair:'#382a25',ambient:'Stara cesta proti severu vodi v Sive zobe. Nova se konča pri gostilni.'},
  {id:'brina',name:'Zeliščarka Brina',x:54*T,y:52*T,body:'#4e704f',hair:'#6c4934',ambient:'Mesečnica ponoči sveti. Podnevi se samo pretvarja, da je navadna roža.'},
  {id:'gostilnicar',name:'Gostilničar Lovro',x:47*T,y:55*T,body:'#70533f',hair:'#33261f',ambient:'Pri Srebrnem petelinu ne strežemo goblinov. Razen če plačajo vnaprej.'},
  {id:'meta',name:'Pastirica Meta',x:30*T,y:72*T,body:'#6e7652',hair:'#a9845e',ambient:'Srne pridejo do polj tik pred dežjem. Bolje napovedujejo vreme kot žreci.'},
  {id:'jan',name:'Kmet Jan',x:39*T,y:70*T,body:'#786546',hair:'#55402d',ambient:'Letos je zemlja dobra. Malo preveč dobra. Kot da nekaj diha pod njo.'},
  {id:'ana',name:'Mlinarica Ana',x:67*T,y:96*T,body:'#6b7782',hair:'#cfbd9b',ambient:'Jure govori z reko. Reka mu odgovarja, vendar nikoli istega dne.'},
  {id:'mostar',name:'Mostar Ožbej',x:58*T,y:74*T,body:'#5d5b4b',hair:'#aaa087',ambient:'Ta most je star dvesto let. Vsaj polovica kamnov je še prvotnih.'},
  {id:'dren',name:'Dren iz Brezovice',x:145*T,y:51*T,body:'#5d7154',hair:'#6c4d34',ambient:'Brezovica je majhna, a naš gozd je večji od vseh mestnih zgodb.'},
  {id:'vesna',name:'Vesna',x:151*T,y:47*T,body:'#7d6b56',hair:'#d2b77d',ambient:'Vilinci kupujejo med, vendar nikoli ne povedo, za kaj ga potrebujejo.'},
  {id:'orel',name:'Lovec Orel',x:156*T,y:55*T,body:'#455b47',hair:'#342a22',ambient:'Volk, ki te opazuje predolgo, morda ni volk.'},
  {id:'jelka',name:'Čebelarka Jelka',x:149*T,y:57*T,body:'#7c744c',hair:'#76533b',ambient:'Čebele ne letijo proti Velesovi jami. Pametnejše so od pustolovcev.'},
  {id:'durin',name:'Rudar Dobromir',x:78*T,y:21*T,body:'#665447',hair:'#b7aa96',dwarf:true,ambient:'Modra žila gre globlje od naše najnižje dvorane.'},
  {id:'milka',name:'Krčmarica Milka',x:87*T,y:22*T,body:'#735f4e',hair:'#4d3528',dwarf:true,ambient:'Škratovsko pivo ni močno. Tla so samo nenavadno mehka.'},
  {id:'tisa',name:'Vilinka Tisa',x:165*T,y:39*T,body:'#607457',hair:'#ddd2ad',elf:true,ambient:'Beli gaj dovoli vstop vsakomur. Odhod je bolj izbirčen.'},
  {id:'lipan',name:'Vilinec Lipan',x:176*T,y:38*T,body:'#526b68',hair:'#b9b69a',elf:true,ambient:'Poslušaj brezove liste. Veter govori hitreje od ljudi.'}
);
npcs.push(
  {id:'knez',name:'Knez Kresnik',x:52*T,y:48*T,body:'#76583e',hair:'#d1bd8e',ambient:'Mesto stoji na žerjavici stare prisege. Nihče več ne pomni njenih besed.'},
  {id:'oznanjevalec',name:'Oznanjevalec Jurij',x:45*T,y:51*T,body:'#7b3f36',hair:'#d0b88e',ambient:'Poslušajte! Severna vrata ostajajo odprta, dokler troli ne najdejo ključa.'},
  {id:'berač',name:'Slepi Matevž',x:37*T,y:55*T,body:'#4c4c44',hair:'#8c8878',ambient:'Pod trgom teče starejša cesta. Slišim vozove, čeprav je zasuta.'},
  {id:'tat',name:'Urh Brezprsti',x:55*T,y:61*T,body:'#394943',hair:'#2c2922',ambient:'Prstov mi niso vzeli. Sam sem jih dal v varstvo.'},
  {id:'pevka',name:'Pevka Maruša',x:42*T,y:58*T,body:'#6c4f72',hair:'#3c2924',ambient:'Poznam pesem o Kralju Matjažu. Zadnji verz pojem samo pod zemljo.'},
  {id:'cebelar',name:'Čebelar Ambrož',x:34*T,y:47*T,body:'#7b7147',hair:'#5c412d',ambient:'Čebele se vračajo z zlatim prahom iz smeri gora.'},
  {id:'straza2',name:'Stražarka Katarina',x:56*T,y:50*T,body:'#52615b',hair:'#6b4a35',ambient:'V kanalizaciji ni podgan. Nekaj jih je pojedlo.'},
  {id:'loncar',name:'Lončar Blaž',x:38*T,y:62*T,body:'#806047',hair:'#4e3829',ambient:'Glino jemljem ob reki. Zadnja kepa je ponoči šepetala.'},
  {id:'usnjar',name:'Usnjar Svit',x:50*T,y:58*T,body:'#654c3c',hair:'#35271f',ambient:'Trolska koža uniči dobro rezilo in slab pogovor.'},
  {id:'kuharica',name:'Kuharica Manca',x:48*T,y:54*T,body:'#80634f',hair:'#b9a184',ambient:'Za enolončnico potrebuješ korenje, čebulo in skrivnost. Skrivnost dodaj zadnjo.'},
  {id:'grobar',name:'Grobar Tobija',x:33*T,y:44*T,body:'#3f4a42',hair:'#777367',ambient:'Pokopališče je polno, kostnica pa nikoli. Ne razumem matematike.'},
  {id:'redovnica',name:'Sestra Lucija',x:47*T,y:45*T,body:'#565b69',hair:'#bbb4a2',ambient:'Staro svetišče ni posvečeno nobenemu svetniku, ki bi ga cerkev priznala.'},
  {id:'karavanar',name:'Karavanar Samo',x:35*T,y:50*T,body:'#6c614b',hair:'#473325',ambient:'Pot do Brezovice je varna. To pomeni, da razbojniki čakajo drugje.'},
  {id:'orodjar',name:'Orodjar Gašper',x:53*T,y:53*T,body:'#556a65',hair:'#694b34',ambient:'Dober kramp odpre rudnik. Odličen kramp odpre težave.'},
  {id:'ucenjak',name:'Učenjakinja Sonja',x:44*T,y:46*T,body:'#4f5d7b',hair:'#9c7452',ambient:'Ajdovski kamni niso grobovi. So opozorilne table, le da ne poznamo pisave.'}
);
[['vrtnar','Vrtnar Rudi',36,48],['tkalka','Tkalka Polona',40,46],['sodar','Sodar Marko',54,46],['ribar','Ribič Erazem',56,57],['vajenec','Vajenec Nace',51,50],['perica','Perica Špela',55,55],['ucitelj','Učitelj Andrej',43,61],['zidar','Zidar Branko',37,60],['mesar','Mesar Klemen',49,61],['pisarka','Pisarka Ema',46,48],['romar','Romar Pavel',34,52],['babica','Babica Roza',41,55]].forEach((v,i)=>npcs.push({id:v[0],name:v[1],x:v[2]*T,y:v[3]*T,body:['#64705a','#715b67','#6c604c'][i%3],hair:['#4a3528','#a88d70','#6d5540'][i%3],ambient:['Vsaka hiša v mestu skriva eno dobro zgodbo in dve slabi.','Včasih ponoči pod tlakom zagorijo drobne iskre.','Če greš pod mesto, vzemi svetilko in nekoga počasnejšega od sebe.'][i%3]}));
npcs.push({id:'brund',name:'Brund Kamnojedi',x:72*T,y:16*T,body:'#65704f',hair:'#454333',troll:true,ambient:'Mostu ne čuvam. Most čuva mene. Če imaš hruško, sva prijatelja.'},{id:'pehta',name:'Pehta',x:188*T,y:51*T,body:'#465945',hair:'#b3ada0',ambient:'Gozd ne kaznuje. Samo vrne, kar mu prineseš.'},{id:'kurent',name:'Korant Rogati',x:28*T,y:76*T,body:'#766048',hair:'#28231d',ambient:'Ko zazvonim, zima beži. Včasih pa zbeži tudi pamet.'},{id:'sojenica',name:'Tretja sojenica',x:161*T,y:30*T,body:'#7e8580',hair:'#e0d9c2',ambient:'Vidim tri konce tvoje poti. V dveh zmagaš. V enem razumeš.'});
const slavicNames={mira:'Miroslava',iva:'Živana',grub:'Vojvoda Gromobor',nib:'Vojvoda Črnomir',lada:'Lada iz Belega gaja',bor:'Kovač Borislav',radovan:'Žrec Radovan',miller:'Mlinar Jaromir',vid:'Stražar Vseslav',neza:'Trgovka Milorada',rok:'Kovač Ratibor',ajda:'Bogdana',tine:'Pek Tihomir',bojan:'Mestni pisar Bogumil',zala:'Zorislava',brina:'Zeliščarka Dobrova',gostilnicar:'Gostilničar Ljubomir',meta:'Pastirica Vesna',jan:'Kmet Dragomir',ana:'Mlinarica Milena',mostar:'Mostar Stanislav',dren:'Dren iz Brezovice',vesna:'Vesna',orel:'Lovec Orlovit',jelka:'Čebelarka Jasna',durin:'Rudar Dobromir',milka:'Krčmarica Miloslava',tisa:'Vilinka Tihoslava',lipan:'Vilinec Svetovid',knez:'Knez Svetopolk',oznanjevalec:'Oznanjevalec Branibor',berač:'Slepi Gostomisl',tat:'Vuk Brezprsti',pevka:'Pevka Zdeslava',cebelar:'Čebelar Medved',straza2:'Stražarka Vladislava',loncar:'Lončar Radogost',usnjar:'Usnjar Vukmir',kuharica:'Kuharica Dragana',grobar:'Grobar Tihoslav',redovnica:'Žerjavna varuhinja Milica',karavanar:'Karavanar Samorad',orodjar:'Orodjar Goran',ucenjak:'Učenjakinja Premislava',vrtnar:'Vrtnar Cvetomir',tkalka:'Tkalka Ljubava',sodar:'Sodar Stanibor',ribar:'Ribič Radoslav',vajenec:'Vajenec Nemir',perica:'Perica Danica',ucitelj:'Učitelj Dobromisl',zidar:'Zidar Branimir',mesar:'Mesar Vukota',pisarka:'Pisarka Zorana',romar:'Romar Radogost',babica:'Babica Grozdana'};for(const n of npcs)if(slavicNames[n.id])n.name=slavicNames[n.id];
for(const n of npcs){const tx=n.x/T,ty=n.y/T;if(tx>51&&tx<61&&ty>40&&ty<66){n.x=(48+(n.id.length%3))*T;n.y+=(n.id.length%3-1)*10}}
const cityPlots=[[32,43,'#56392b',0],[36,43,'#683f2d',1],[40,43,'#49372d',0],[49,43,'#68412f',1],[32,53,'#49362a',1],[36,53,'#704532',0],[49,53,'#4b372b',1],[32,57,'#56382d',2],[36,57,'#49372d',0],[40,57,'#6c4230',1],[49,57,'#4a382e',0],[32,61,'#6b4130',2],[36,61,'#4d382b',1],[40,61,'#643f30',0],[49,61,'#50372a',2],[34,65,'#49372d',0],[39,65,'#68412f',1],[44,65,'#56392b',0],[49,65,'#49372d',1]];
const standard={x:109*T,y:49*T},perunShrine={x:209*T,y:12*T},riverAltar={x:59*T,y:113*T},camp={x:17*T,y:55*T};
const portals=[{id:'miraHouse',name:'Mirina hiša',x:13*T,y:47*T},{id:'dwarfHall',name:'Dvorana Sivih zob',x:82*T,y:17*T},{id:'velesCave',name:'Velesova jama',x:184*T,y:25*T},{id:'elfLodge',name:'Hiša Belega gaja',x:172*T,y:32*T},{id:'riverMill',name:'Juretov mlin',x:61*T,y:92*T},{id:'kresnikInn',name:'Gostilna Srebrni petelin',x:47*T,y:55*T},{id:'kresnikForge',name:'Kresnikovska kovačija',x:49*T,y:47*T},{id:'kresnikHall',name:'Knežji dvor',x:49*T,y:51*T},{id:'kresnikTemple',name:'Svetišče žerjavice',x:47*T,y:45*T},{id:'kresnikSewer',name:'Kresnikovska kanalizacija',x:45*T,y:53*T},{id:'matjazCave',name:'Votla gora Kralja Matjaža',x:91*T,y:10*T},{id:'ajdTomb',name:'Ajdovska grobnica',x:132*T,y:98*T},{id:'trollMine',name:'Zapuščeni trolski rudnik',x:74*T,y:13*T},{id:'vilenica',name:'Jama Vilenica',x:181*T,y:43*T}];
const landmarks=[{name:'Jelševa vas',x:17,y:50,type:'town'},{name:'Kresnikovo',x:45,y:53,type:'town'},{name:'Brezovica',x:150,y:51,type:'town'},{name:'Rdeči tabor',x:100,y:44,type:'danger'},{name:'Modri tabor',x:119,y:57,type:'danger'},{name:'Beli gaj',x:170,y:35,type:'town'},{name:'Perunove ruševine',x:198,y:20,type:'danger'},{name:'Matjaževo pod Peco',x:86,y:16,type:'town'},{name:'Mlin ob Kolpi',x:62,y:94,type:'town'},{name:'Velesova jama',x:184,y:25,type:'danger'},{name:'Ajdovska grobnica',x:132,y:98,type:'danger'},{name:'Jama Vilenica',x:181,y:43,type:'danger'}];
portals.push({id:'shadowMaze',name:'Labirint treh senc',x:136*T,y:109*T});
const exploreSites=[
  {id:'charcoal',name:'Oglarska kopa',type:'camp',x:43*T,y:31*T,reward:'coin',amount:12,skill:'forage',xp:10,text:'Kopa je še topla. Med pepelom najdeš oglarske kovance in v skorjo vrezan znak treh sonc.'},
  {id:'wayshrine',name:'Znamenje svete Eme',type:'shrine',x:72*T,y:67*T,reward:'mushroom',amount:2,skill:'forage',xp:12,text:'Pod lesenim znamenjem je nekdo pustil suhe gobe za naslednjega popotnika.'},
  {id:'giantstep',name:'Stopinja ajda',type:'bones',x:104*T,y:27*T,reward:'ore',amount:1,skill:'mining',xp:18,text:'V skali je stopinja, večja od voza. V peti se modro lesketa odkrušena ruda.'},
  {id:'stonecircle',name:'Krog sojenic',type:'stones',x:112*T,y:82*T,reward:'berry',amount:3,skill:'forage',xp:15,text:'Trije kamni mečejo štiri sence. V sredini rastejo jagode, ki jih ptice ne kljuvajo.'},
  {id:'drownedcart',name:'Potopljeni voz',type:'wreck',x:58*T,y:36*T,reward:'coin',amount:20,skill:'forage',xp:14,text:'Pol voza je pogoltnil breg. V železnem okovu je ostala skrita mošnja.'},
  {id:'apiary',name:'Zapuščeni čebelnjak',type:'apiary',x:140*T,y:64*T,reward:'mushroom',amount:1,skill:'forage',xp:16,text:'Čebel ni več, toda panji še dišijo po kostanju. Za enim leži zdravilni zavitek.'},
  {id:'shepherd',name:'Pastirsko zavetje',type:'hut',x:125*T,y:101*T,reward:'coin',amount:14,skill:'combat',xp:12,text:'Na steni so zareze za vsako noč, ko je Divja jaga prečkala močvirje.'},
  {id:'hunter',name:'Lovčeva opazovalnica',type:'tower',x:194*T,y:62*T,reward:'berry',amount:2,skill:'combat',xp:16,text:'Z višine vidiš stare stečine med drevesi. Lovec je pod desko skril zalogo.'},
  {id:'velesidol',name:'Velesov mejnik',type:'idol',x:181*T,y:71*T,reward:'coin',amount:25,skill:'forage',xp:20,text:'Kamniti obraz gleda navzdol, proti koreninam. Darovi pred njim so prastari — eden ni.'},
  {id:'kurentfire',name:'Ugaslo kurentovo ognjišče',type:'fire',x:29*T,y:81*T,reward:'wood',amount:2,skill:'woodcut',xp:14,text:'Okoli pepela ležijo trakovi in zlomljen zvonec. Žerjavica se pri tvojem dotiku še enkrat zasveti.'}
];
const rnd=(x,y,n=0)=>{const v=Math.sin(x*127.1+y*311.7+n*71.9)*43758.5453;return v-Math.floor(v)};
function riverCenter(ty){return 54+Math.sin(ty*.13)*5}
function waterTile(tx,ty){const river=Math.abs(tx-riverCenter(ty))<2.2&&!((ty>47&&ty<51)||(ty>72&&ty<76));const lake=tx>119&&tx<143&&ty>65&&ty<86&&Math.hypot((tx-131)/1.2,ty-76)<10;return tx<1||ty<1||tx>=WW-1||ty>=WH-1||river||lake}
function biomeAt(x,y){const tx=x/T,ty=y/T;if(tx>91&&tx<129&&ty>34&&ty<65)return'goblin';if(tx>62&&tx<110&&ty<32)return'mountain';if(tx>150&&tx<190&&ty>24&&ty<56)return'forest';if(tx>118&&ty>68)return'marsh';if(tx>185&&ty<34)return'ruins';if(Math.abs(tx-riverCenter(ty))<7)return'river';if(tx<38&&ty>39&&ty<69)return'village';return'forest'}
function pathTile(tx,ty){return(ty>=48&&ty<=50&&tx>5&&tx<178)||(ty>=56&&ty<=58&&tx>29&&tx<58)||(tx>=44&&tx<=46&&ty>47&&ty<64)||(tx>=81&&tx<=83&&ty>15&&ty<50)||(ty>=34&&ty<=36&&tx>145&&tx<188)||(tx>=168&&tx<=170&&ty>34&&ty<50)||(tx>=99&&tx<=101&&ty>41&&ty<51)||(ty>=56&&ty<=58&&tx>99&&tx<123)||(tx>=108&&tx<=110&&ty>48&&ty<58)||(tx>=61&&tx<=63&&ty>48&&ty<116)||(ty>=92&&ty<=94&&tx>53&&tx<72)||(tx>=149&&tx<=151&&ty>46&&ty<58)}
function baseState(){return{x:17*T,y:57*T,hp:100,maxHp:100,xp:0,level:1,quest:0,scene:'world',weapon:'sword',armor:null,shield:null,inventory:{axe:1,sword:1,pick:1,wood:0,mushroom:1,berry:0,flower:0,ore:0,coin:0,banner:0,scrap:0,bell:0,thunderRune:0,waterPearl:0,bones:0,bread:0,hide:0,goblinVest:0,ironScimitar:0,goldScimitar:0,sunShield:0},skills:{woodcut:0,forage:0,combat:0,mining:0,spirit:0,defence:0},settings:{weatherFx:true,screenShake:true},harvested:{},chests:{},discoveries:{},bossDead:false,stormDead:false,waterDead:false,dir:-Math.PI/2,playtime:0}}
function hydrate(s){state=Object.assign(baseState(),s||{});state.inventory=Object.assign(baseState().inventory,s?.inventory||{});state.skills=Object.assign(baseState().skills,s?.skills||{});state.settings=Object.assign(baseState().settings,s?.settings||{});state.harvested=s?.harvested||{};state.chests=s?.chests||{};state.discoveries=s?.discoveries||{};player={walk:0,attack:0,attackHit:false,invuln:0,action:null}}
function load(){let s=null;try{s=JSON.parse(localStorage.getItem('mah-save-current')||localStorage.getItem('mahInZerjavicaV2')||'null')}catch(e){}hydrate(s)}
function save(){state.playtime+=saveClock;saveClock=0;localStorage.setItem('mah-save-current',JSON.stringify(state));if(state.activeSlot)localStorage.setItem('mah-save-'+state.activeSlot,JSON.stringify(state))}
function loadSlot(i){try{const s=JSON.parse(localStorage.getItem('mah-save-'+i));if(!s)return;hydrate(s);state.activeSlot=i;resources.length=enemies.length=fireflies.length=clouds.length=0;buildWorld();updateUI();menuOpen=false;$('mainMenu').classList.add('hidden');transitionTip();notify('Naložena shranjena igra '+i)}catch(e){notify('Shranjene igre ni mogoče naložiti.')}}
function saveSlot(i){state.activeSlot=i;save();renderSlots();notify('Igra shranjena v režo '+i);A.play('quest')}
function renderSlots(){const box=$('saveSlots');box.innerHTML=[1,2,3].map(i=>{let s=null;try{s=JSON.parse(localStorage.getItem('mah-save-'+i))}catch(e){}const label=s?`${quests[s.quest]?.[0]||'Pustolovščina'} · ${Math.floor((s.playtime||0)/60)} min`:'Prazna reža';return`<div class="save-slot"><span>Reža ${i}<small>${label}</small></span><button data-save="${i}">Shrani</button>${s?`<button data-load="${i}">Naloži</button>`:''}</div>`}).join('');box.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>saveSlot(+b.dataset.save));box.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>loadSlot(+b.dataset.load))}
function addResource(type,tx,ty,id){resources.push({type,x:tx*T,y:ty*T,id,hp:type==='tree'?3:type==='rock'?4:1,max:type==='tree'?3:type==='rock'?4:1,bump:0})}
function enemy(type,tx,ty,id){const stats={slime:[4,34],wolf:[6,62],goblin:[7,48],boss:[28,48],mountainTroll:[32,28],riverTroll:[24,32],caveTroll:[27,36],deer:[1,46],chicken:[1,22]}[type];return{type,x:tx*T,y:ty*T,id,hp:stats[0],max:stats[0],speed:stats[1],dead:type==='boss'&&state.bossDead,hit:0,attack:0,phase:rnd(tx,ty)*6.28,passive:type==='deer'||type==='chicken'}}
function buildWorld(){
  for(let y=2;y<WH-2;y++)for(let x=2;x<WW-2;x++){if(waterTile(x,y)||pathTile(x,y)||(x>8&&x<30&&y>42&&y<63)||(x>31&&x<58&&y>43&&y<64)||(x>142&&x<159&&y>44&&y<61)||(x>94&&x<124&&y>39&&y<61)||(x>162&&x<180&&y>28&&y<43)||(x>76&&x<90&&y>12&&y<24)||(x>190&&x<207&&y>14&&y<27)||(x>203&&x<215&&y>6&&y<19)||(x>54&&x<65&&y>108&&y<119)||(x>56&&x<69&&y>88&&y<100))continue;const b=biomeAt(x*T,y*T),r=rnd(x,y);if(b==='mountain'){if(r>.77)addResource('rock',x,y,'r'+x+'_'+y);else if(r>.71)addResource('tree',x,y,'t'+x+'_'+y)}else if(b==='marsh'){if(r>.93)addResource('tree',x,y,'t'+x+'_'+y);else if(r>.81&&r<.84)addResource('mushroom',x,y,'m'+x+'_'+y)}else{if(r>.91)addResource('tree',x,y,'t'+x+'_'+y);else if(r<.021)addResource('rock',x,y,'r'+x+'_'+y);else if(r>.82&&r<.84)addResource(x>145&&y<58?'flower':rnd(x,y,7)>.5?'berry':'mushroom',x,y,'f'+x+'_'+y)}}
  [[35,43],[40,61],[65,68],[73,37],[87,32],[105,71],[115,77],[130,89],[152,65],[187,74]].forEach((p,i)=>addResource('berry',p[0],p[1],'berry'+i));[[72,22],[79,27],[87,18],[91,31],[68,15],[98,20],[194,34],[202,42]].forEach((p,i)=>addResource('rock',p[0],p[1],'ore'+i));[[154,32],[160,44],[174,28],[181,42],[188,36],[150,52],[176,50]].forEach((p,i)=>addResource('flower',p[0],p[1],'moon'+i));
  [[31,55],[42,38],[65,58],[75,70],[86,43],[145,82],[188,61]].forEach((p,i)=>enemies.push(enemy('slime',p[0],p[1],'s'+i)));[[49,29],[70,40],[80,65],[93,27],[137,35],[158,60],[177,71],[199,48]].forEach((p,i)=>enemies.push(enemy('wolf',p[0],p[1],'w'+i)));for(let i=0;i<20;i++)enemies.push(enemy('goblin',94+(i*7)%31,36+(i*11)%31,'g'+i));
  [[69,14],[76,9],[92,18]].forEach((p,i)=>enemies.push(enemy('mountainTroll',p[0],p[1],'mt'+i)));[[57,82],[64,105]].forEach((p,i)=>enemies.push(enemy('riverTroll',p[0],p[1],'rt'+i)));[[177,27],[134,95],[75,11]].forEach((p,i)=>enemies.push(enemy('caveTroll',p[0],p[1],'ct'+i)));[[31,69],[39,74],[150,60],[167,47],[67,97]].forEach((p,i)=>enemies.push(enemy('deer',p[0],p[1],'deer'+i)));for(let i=0;i<9;i++)enemies.push(enemy('chicken',35+(i*5)%20,45+(i*7)%17,'hen'+i));
  if(state.quest===6&&!state.bossDead)enemies.push(enemy('boss',111,48,'boglug'));if(state.quest===18&&!state.stormDead)enemies.push(enemy('boss',207,14,'gromovnik'));if(state.quest===23&&!state.waterDead)enemies.push(enemy('boss',60,111,'povodni'));
  for(let i=0;i<120;i++)fireflies.push({x:rnd(i,2)*WW*T,y:rnd(i,9)*WH*T,p:rnd(i,5)*6.28,s:7+rnd(i,8)*12});for(let i=0;i<12;i++)clouds.push({x:rnd(i,4)*W,y:30+rnd(i,8)*190,w:55+rnd(i,3)*90,s:5+rnd(i,6)*9});
}
function solidAt(x,y,r=10){if(state.scene!=='world')return x<56||x>W-56||y<82||y>H-55;if(waterTile(Math.floor(x/T),Math.floor(y/T)))return true;for(const h of cityPlots){const hx=h[0]*T,hy=h[1]*T,dx=Math.abs(x-hx),dy=y-hy;if(dx<43+r&&dy>-73-r&&dy<8+r&&!(dx<11&&dy>-20))return true}for(const n of npcs)if(Math.hypot(x-n.x,y-n.y)<r+12)return true;for(const o of resources)if(!state.harvested[o.id]&&o.type!=='mushroom'&&o.type!=='berry'&&o.type!=='flower'&&Math.hypot(x-o.x,y-o.y)<r+13)return true;return false}
function notify(s){clearTimeout(toastTimer);ui.toast.textContent=s;ui.toast.classList.add('show');toastTimer=setTimeout(()=>ui.toast.classList.remove('show'),2200)}
function setWeather(kind,duration=32){weather=kind;weatherUntil=time+duration;document.querySelector('.weather').className='weather '+kind;if(kind==='storm')notify('Nebo se je razklalo. Prihaja Perunova nevihta.')}
function emit(x,y,color,n=9){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*110,vy:-25-Math.random()*90,life:.45+Math.random()*.55,color,size:2+Math.random()*3})}
function floatText(s,x,y,color='#f1d586'){floaters.push({s,x,y,color,life:1})}
function addItem(k,n=1){state.inventory[k]=(state.inventory[k]||0)+n;A.play('pickup');floatText('+'+n+' '+items[k].name,state.x,state.y-24);updateUI();save()}
function gain(skill,n){state.skills[skill]+=n;const old=state.level;state.xp+=n;state.level=1+Math.floor(Math.sqrt(state.xp/45));if(state.level>old){state.maxHp+=10;state.hp=state.maxHp;A.play('level');notify('Raven '+state.level+'! Moč v tebi raste.')}updateUI()}
function useMushroom(){if(!state.inventory.mushroom||state.hp>=state.maxHp)return;state.inventory.mushroom--;state.hp=Math.min(state.maxHp,state.hp+35);A.play('heal');emit(state.x,state.y,'#9fd46b',15);notify('Žerjavna toplota zaceli rane.');updateUI();save()}
function speak(name,lines,end){dialogue={name,lines,i:0,end};showLine()}
function showLine(){ui.speaker.textContent=dialogue.name;ui.portrait.textContent=dialogue.name[0];ui.text.textContent=dialogue.lines[dialogue.i];ui.dialogue.classList.remove('hidden');A.play('talk')}
function nextLine(){if(!dialogue)return;dialogue.i++;if(dialogue.i>=dialogue.lines.length){ui.dialogue.classList.add('hidden');const fn=dialogue.end;dialogue=null;if(fn)fn()}else showLine()}
function talkMira(){
  if(state.quest===0)speak('Mira',['Arin, ravno prav. Goblini z vzhoda so spet na bojni nogi. Tokrat zaradi barve zastave.','Rdečekape pravijo, da je rdeča pogumna. Modri škornji trdijo, da je modra pametna. Oboji so oboroženi in nihče ni ne eno ne drugo.','Poišči generala Gruba v Rdečem taboru onkraj reke. Poskusi izvedeti, kaj bi ga spravilo za isto mizo z generalom Nibom.'],()=>setQuest(1,'Nova naloga: Tri barve prepira'));
  else if(state.quest<4)speak('Mira',['Sledi vzhodni poti čez kamniti most. Na razpotju bodo njihove grde zastave pokazale smer.']);
  else if(state.quest===4)speak('Mira',['Mrakove jagode za modro, modra ruda za sijaj ... in malo pepela, da užaliva obe strani enako.','Tukaj je prazno praporje. Odnesi ga na Zborni kol v središču obeh taborov. Če vprašajo, je barva »dostojanstveno blatna«.'],()=>{state.inventory.berry-=5;state.inventory.ore-=3;state.inventory.banner=1;setQuest(5,'Prejel si nevtralno praporje.');A.play('quest')});
  else if(state.quest===7)speak('Mira',['Torej je Boglug pojedel zastavo in nato še skoraj tebe? To je nenavadno dober diplomatski izid.','Brez simbola se goblini nimajo za kaj prepirati. Dolina ima mir — vsaj do naslednje barve.'],()=>{state.inventory.coin+=80;completeQuest('Tri barve prepira','80 bakrencev\n900 bojnih EXP\nDostop do Belega gaja',9);gain('combat',900)});
  else speak('Mira',['Kadar diplomacija odpove, očitno potrebujemo več blata.']);
}
function talkGrub(){if(state.quest===1)speak('General Grub',['Stoj! Jaz General Grub, devetnajsti svojega imena! Rdeča najboljša barva. Tudi kri rdeča. Tudi juha, ko kuhar zameša lonec.','Nib pravi modra boljša. Pojdi k njemu. Povej mu Grub sprejme samo barvo, ki je boljša od obeh!'],()=>setQuest(2,'Poišči generala Niba v Modrem taboru.'));else if(state.quest>=5)speak('General Grub',['Blatna zastava grda. To pomeni poštena. Grub skoraj zadovoljen.']);else speak('General Grub',['Nib živi jugovzhodno. Sledi modrim cunjam in vonju slabe juhe.'])}
function talkNib(){if(state.quest===2)speak('General Nib',['Grub je bedak. Rdeča privabi bike in davkarje. Modra je barva strategije!','Toda barva boljša od obeh? Hm. Vaša Mira pozna barvila. Prinesi ji pet mrakovih jagod in tri kose modre rude. Naj naredi barvo, ki je nihče ne more zahtevati zase.'],()=>setQuest(3,'Zberi sestavine za nevtralno barvo.'));else speak('General Nib',['Ruda je v gorah severno od reke. Jagode rastejo ob poteh in v močvirju.'])}
function talkIva(){speak('Iva',['Zemljevid odpreš s tipko M. Rumeni diamant vedno pokaže naslednji cilj.','Če se izgubiš: reka deli dolino, dva kamnita mostova pa jo spet sestavita.'])}
function talkLada(){if(state.quest===9)speak('Lada iz Belega gaja',['Dobrodošel pod vejami, Arin. Zlatorog je izgubil srebrni zvonček. Brez njegovega glasu se poti pod Triglavom zapirajo.','Naberi šest mesečnic v Belem gaju. Njihov vonj bo razkril vhod v Velesovo jamo.'],()=>setQuest(10,'Nova naloga: Srebrni glas Zlatoroga'));else if(state.quest===11)speak('Lada iz Belega gaja',['Mesečnice kažejo proti črni pečini na vzhodu. Vstopi v Velesovo jamo in poišči srebrni zvonček.']);else if(state.quest===12)speak('Lada iz Belega gaja',['Spet slišim njegov glas. Zlatorog ti dovoljuje prehod v svoje kraljestvo.','Vzemi jekleno rezilo Belega gaja. Naj bo tvoja roka hitra, srce pa počasno.'],()=>{state.inventory.steelSword=1;completeQuest('Srebrni glas Zlatoroga','Jekleni meč\n1.200 nabiralniških EXP\nVstop v kraljestvo Zlatoroga',13);gain('forage',1200)});else speak('Lada iz Belega gaja',['V Belem gaju ne govorimo glasno. Drevesa si zapomnijo ton.'])}
function talkBor(){if(state.quest===13)speak('Kovač Bor',['Velesove sence polzijo iz razpok. Moje kladivo jih ne doseže, tvoje rezilo pa jih morda bo.','Prinesi pet modrih rud in tri goblinske zaponke. Skujem ti orožje, ki pozna temo.'],()=>setQuest(14,'Nova naloga: Velesova senca'));else if(state.quest===15)speak('Kovač Bor',['Dobra ruda. Slabe zaponke. Ravno prav za črno rezilo.','Ne glej predolgo v njegovo kovino. Včasih pogleda nazaj.'],()=>{state.inventory.ore-=5;state.inventory.scrap-=3;state.inventory.blackSword=1;completeQuest('Velesova senca','Črno rezilo Velesa\n1.500 rudarskih EXP\nDostop do škratovskih dvoran',16);gain('mining',1500)});else speak('Kovač Bor',['Ruda poje pod krampom. Če ne poje, udari močneje.'])}
function talkRadovan(){if(state.quest===16)speak('Žrec Radovan',['Perun je jezen. Vrhovi so tihi, čeprav bi morali grmeti. Nekdo je ukradel iskro z njegovega oltarja.','Pojdi do Perunovega svetišča na skrajnem severovzhodu. Ko se začne nevihta, ne beži.'],()=>setQuest(17,'Nova naloga: Perunov ukradeni grom'));else if(state.quest===19)speak('Žrec Radovan',['Grom se je vrnil v nebo, runa pa je izbrala tebe.','Runsko rezilo lahko nosi le bojevnik dvanajste ravni. Do takrat naj te spominja, kam raste pogum.'],()=>{state.inventory.runeSword=1;state.inventory.thunderRune=1;completeQuest('Perunov ukradeni grom','Perunovo runsko rezilo\nPerunova runa\n2.000 bojnih EXP',20);gain('combat',2000)});else speak('Žrec Radovan',['Perun sliši dejanja. Molitve so le njihov odmev.'])}
function talkMiller(){if(state.quest===20)speak('Mlinar Jure',['Reka mi je ponoči odnesla mlinsko kolo, zjutraj pa ga vrnila iz čistega zlata. To ni darilo. To je opozorilo.','Prinesi tri polena in štiri žerjavne gobe k rečnemu oltarju južno od mlina. Povodni mož posluša samo tiste, ki nekaj vrnejo vodi.'],()=>setQuest(21,'Nova naloga: Nevesta iz globine'));else if(state.quest===24)speak('Mlinar Jure',['Biser! Torej reka sprejema mir. Morda bom zlato kolo vseeno prebarval.','Zlatorog ti pošilja zadnje darilo: zmajski meč, skovan iz luske, ki je nikoli ni imel noben zmaj.'],()=>{state.inventory.dragonSword=1;completeQuest('Nevesta iz globine','Zmajski meč Zlatoroga\nBiser Povodnega moža\n3.000 pustolovskih EXP\nKraljestvo Zlatoroga je odprto',25);gain('combat',3000)});else speak('Mlinar Jure',['Reka vedno vzame ovinek, kadar človek zahteva ravno pot.'])}
function talkAmbient(n){speak(n.name,[n.ambient||'Dolina je danes nenavadno tiha.'])}
function completeQuest(title,reward,next){ui.rewardTitle.textContent=title;ui.rewardText.textContent='Dobil si:\n'+reward;ui.questReward.classList.remove('hidden');state.quest=next;A.play('quest');save();updateUI()}
function setQuest(q,msg){state.quest=q;if(q===3&&state.inventory.berry>=5&&state.inventory.ore>=3)state.quest=4;if(q===10&&state.inventory.flower>=6)state.quest=11;if(q===14&&state.inventory.ore>=5&&state.inventory.scrap>=3)state.quest=15;if(q===21&&state.inventory.wood>=3&&state.inventory.mushroom>=4)state.quest=22;A.play('quest');if(msg)notify(msg);updateUI();save()}
function activateStandard(){if(state.quest!==5){notify('Na kolu visijo ostanki številnih slabih odločitev.');return}state.inventory.banner=0;setQuest(6,'Nekaj velikega prihaja iz grmovja ...');shake=14;emit(standard.x,standard.y,'#e5b654',35);const b=enemy('boss',111,48,'boglug');enemies.push(b);speak('Boglug, jedec praporov',['BLOP! Nova zastava! Boglug poje barve. Potem poje diplomata.'])}
function activatePerun(){if(state.quest!==17){notify('Oltar je hladen, toda zrak diši po dežju.');return}setQuest(18,'Perunov grom je prebudil varuha!');setWeather('storm',45);shake=18;emit(perunShrine.x,perunShrine.y,'#d9e7ff',45);enemies.push(enemy('boss',207,14,'gromovnik'));speak('Gromovnik',['Kdor zahteva grom, mora najprej preživeti njegov glas.'])}
function activateRiver(){if(state.quest!==22){notify('Voda te opazuje brez oči.');return}state.inventory.wood-=3;state.inventory.mushroom-=4;setQuest(23,'Povodni mož je sprejel daritev ... in zahteva preizkus.');setWeather('rain',40);enemies.push(enemy('boss',60,111,'povodni'));speak('Povodni mož',['Ljudje vračate vodi le tisto, česar ne potrebujete. Pokaži mi, kaj si pripravljen braniti.'])}
function transitionTip(){const tips=['Ozke poti so varnejše, a ob njih prežijo razbojniki.','Drži Space za hitre zaporedne udarce.','Vsaka kovina zahteva višjo bojno raven.','Mesečnice rastejo vzhodno od reke.','Vreme spreminja razpoloženje in glasbo doline.'];$('loadingTip').textContent='Namig: '+tips[Math.floor(Math.random()*tips.length)];const s=$('loadingScreen');s.classList.remove('fade','hidden');setTimeout(()=>s.classList.add('fade'),850);setTimeout(()=>s.classList.add('hidden'),1550)}
function enterScene(p){state.returnX=state.x;state.returnY=state.y;state.scene=p.id;state.x=W/2;state.y=H-110;camera.x=camera.y=0;transitionTip();save()}
function leaveScene(){state.scene='world';state.x=state.returnX||camp.x;state.y=(state.returnY||camp.y)+28;transitionTip();save()}
function openChest(){const id=state.scene;if(state.chests[id]){notify('Skrinja je prazna.');return}state.chests[id]=true;if(id==='miraHouse'){state.inventory.ironSword=1;notify('Našel si železni meč!')}else if(id==='dwarfHall'){state.inventory.adamantSword=1;notify('Našel si adamantno rezilo. Zahteva 10. raven.')}else if(id==='velesCave'){state.inventory.bell=1;if(state.quest===11)setQuest(12,'Našel si Zlatorogov zvonček. Vrni se k Ladi.');notify('Srebrni zvonček zazveni v temi.')}else if(id==='elfLodge'){state.inventory.mithrilSword=1;notify('Našel si mitrilni meč. Zahteva 8. raven.')}else{state.inventory.coin+=25;notify('Našel si 25 bakrencev.')}A.play('quest');updateUI();save()}
function discoverSite(site){if(state.discoveries[site.id]){speak(site.name,[site.text]);return}state.discoveries[site.id]=true;state.inventory[site.reward]=(state.inventory[site.reward]||0)+site.amount;gain(site.skill,site.xp);A.play('quest');emit(site.x,site.y,'#e8c86d',24);speak(site.name,[site.text,`ODKRITJE: ${site.name}. Dobil si ${site.amount} × ${items[site.reward].name} in ${site.xp} EXP.`],()=>{updateUI();save()})}
function beginAction(o){if(player.action||player.attack)return;const type=o.type==='tree'?'chop':o.type==='rock'?'mine':'pick';player.action={type,o,t:0,hit:false,total:type==='pick'?.42:.68};state.dir=Math.atan2(o.y-state.y,o.x-state.x)}
function applyAction(a){const o=a.o;if(state.harvested[o.id])return;if(o.type==='tree'||o.type==='rock'){o.hp--;o.bump=1;A.play(o.type==='tree'?'chop':'mine');emit(o.x,o.y,o.type==='tree'?'#a77a43':'#9cabad',9);if(o.hp<=0){state.harvested[o.id]=true;addItem(o.type==='tree'?'wood':'ore');gain(o.type==='tree'?'woodcut':'mining',o.type==='tree'?7:9)}}else{state.harvested[o.id]=true;addItem(o.type);gain('forage',6)}if(state.quest===3&&state.inventory.berry>=5&&state.inventory.ore>=3)setQuest(4,'Sestavine zbrane. Vrni se k Miri.');if(state.quest===10&&state.inventory.flower>=6)setQuest(11,'Mesečnice kažejo pot v Velesovo jamo.');if(state.quest===14&&state.inventory.ore>=5&&state.inventory.scrap>=3)setQuest(15,'Material zbran. Vrni se h kovaču Boru.');if(state.quest===21&&state.inventory.wood>=3&&state.inventory.mushroom>=4)setQuest(22,'Daritev je pripravljena. Pojdi k rečnemu oltarju.');updateUI()}
function interact(){A.init();if(dialogue){nextLine();return}if(mapOpen){toggleMap();return}if(!target)return;const a=target;if(a.kind==='npc'){const fn=({mira:talkMira,iva:talkIva,grub:talkGrub,nib:talkNib,lada:talkLada,bor:talkBor,radovan:talkRadovan,miller:talkMiller}[a.o.id]);(fn||(()=>talkAmbient(a.o)))();return}if(a.kind==='site'){discoverSite(a.o);return}if(a.kind==='standard'){activateStandard();return}if(a.kind==='perun'){activatePerun();return}if(a.kind==='river'){activateRiver();return}if(a.kind==='portal'){enterScene(a.o);return}if(a.kind==='exit'){leaveScene();return}if(a.kind==='chest'){openChest();return}beginAction(a.o)}
function attack(){A.init();if(dialogue||mapOpen||player.action||player.attack)return;player.attack=.23;player.attackHit=false;A.play('sword')}
function attackHit(){for(const e of enemies){if(e.dead)continue;const d=Math.hypot(e.x-state.x,e.y-state.y),ang=Math.atan2(e.y-state.y,e.x-state.x),delta=Math.atan2(Math.sin(ang-state.dir),Math.cos(ang-state.dir));if(d<61&&Math.abs(delta)<1.35){const blade=items[state.weapon]||items.sword,dmg=Math.max(1,blade.weapon+Math.floor(state.level/4));e.hp-=dmg;e.hit=.2;shake=5;A.play('hit');floatText('-'+dmg,e.x,e.y-25,'#ffdc91');emit(e.x,e.y,e.type==='goblin'||e.type==='boss'?'#79954f':'#85b797',10);if(e.hp<=0)kill(e)}}}
function kill(e){e.dead=true;gain('combat',e.type==='boss'?55:e.type==='goblin'?12:e.type==='wolf'?10:7);addItem(e.type==='goblin'||e.type==='boss'?'scrap':'coin',e.type==='boss'?5:1);if(e.id==='boglug'){state.bossDead=true;setQuest(7,'Boglug je premagan. Vrni se k Miri.')}if(e.id==='gromovnik'){state.stormDead=true;setQuest(19,'Gromovnik je premagan. Vrni se k Radovanu.')}if(e.id==='povodni'){state.waterDead=true;state.inventory.waterPearl=1;setQuest(24,'Prejel si biser. Vrni se k mlinarju Juretu.')}if(state.quest===14&&state.inventory.ore>=5&&state.inventory.scrap>=3)setQuest(15,'Material zbran. Vrni se h kovaču Boru.');A.play('quest');emit(e.x,e.y,'#edc568',e.type==='boss'?45:12)}
function hurt(n){if(player.invuln||state.hp<=0)return;state.hp-=n;player.invuln=.85;shake=8;A.play('hurt');floatText('-'+n,state.x,state.y-28,'#ff8478');if(state.hp<=0){state.hp=0;ui.death.classList.remove('hidden')}updateUI()}
function updatePlayer(dt){if(player.action){player.action.t+=dt;if(!player.action.hit&&player.action.t/player.action.total>.48){player.action.hit=true;applyAction(player.action)}if(player.action.t>=player.action.total)player.action=null}if(player.attack){player.attack=Math.max(0,player.attack-dt);if(!player.attackHit&&player.attack<.12){player.attackHit=true;attackHit()}}else if(keys[' ']&&!dialogue&&!mapOpen&&!menuOpen)attack();let dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);const l=Math.hypot(dx,dy)||1;dx/=l;dy/=l;const locked=dialogue||mapOpen||menuOpen||player.action||!ui.questReward.classList.contains('hidden'),speed=locked?0:154;if(dx||dy)state.dir=Math.atan2(dy,dx);const nx=state.x+dx*speed*dt,ny=state.y+dy*speed*dt;if(!solidAt(nx,state.y))state.x=nx;if(!solidAt(state.x,ny))state.y=ny;if(speed&&(dx||dy)){player.walk+=dt*10;if(Math.floor(player.walk*1.8)%8===0&&Math.floor((player.walk-dt*10)*1.8)%8!==0)A.play('step')}player.invuln=Math.max(0,player.invuln-dt);const maxX=state.scene==='world'?(WW-1)*T:W-56,maxY=state.scene==='world'?(WH-1)*T:H-55;state.x=Math.max(state.scene==='world'?T:56,Math.min(maxX,state.x));state.y=Math.max(state.scene==='world'?T:82,Math.min(maxY,state.y))}
function updateEnemies(dt){if(state.scene!=='world')return;for(const e of enemies){if(e.dead)continue;e.hit=Math.max(0,e.hit-dt);e.attack=Math.max(0,e.attack-dt);const d=Math.hypot(state.x-e.x,state.y-e.y);if(e.passive){if(d<105){const a=Math.atan2(e.y-state.y,e.x-state.x);e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt}else{e.x+=Math.cos(time*.35+e.phase)*e.speed*.08*dt;e.y+=Math.sin(time*.29+e.phase)*e.speed*.08*dt}continue}if(d<250&&!dialogue&&!mapOpen&&!menuOpen){const a=Math.atan2(state.y-e.y,state.x-e.x)+Math.sin(time*1.7+e.phase)*.25;e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt;if(d<34&&e.attack<=0){e.attack=1.15;if(e.type==='goblin'||e.type==='boss'||e.type.includes('Troll'))A.play('goblin');const heavy=e.type.includes('Troll');hurt(e.type==='boss'?17:heavy?14:e.type==='goblin'?9:e.type==='wolf'?11:7)}}}}
function nearest(){let b=null,d=55;if(state.scene!=='world'){const exit={x:W/2,y:H-55},chest={x:W/2+135,y:H/2};if(Math.hypot(exit.x-state.x,exit.y-state.y)<d)b={kind:'exit',label:'Zapusti prostor'};if(Math.hypot(chest.x-state.x,chest.y-state.y)<d)b={kind:'chest',label:state.chests[state.scene]?'Preglej prazno skrinjo':'Odpri staro skrinjo'};target=b;ui.prompt.classList.toggle('show',!!b&&!dialogue);ui.prompt.innerHTML=b?'<b>E</b> · '+b.label:'';return}for(const n of npcs){const q=Math.hypot(n.x-state.x,n.y-state.y);if(q<d){d=q;b={kind:'npc',o:n,label:'Govori: '+n.name}}}for(const o of resources){if(state.harvested[o.id])continue;const q=Math.hypot(o.x-state.x,o.y-state.y);if(q<d){d=q;b={kind:'resource',o,label:o.type==='tree'?'Posekaj drevo':o.type==='rock'?'Izkoplji modro rudo':o.type==='berry'?'Naberi mrakove jagode':o.type==='flower'?'Naberi mesečnico':'Naberi žerjavno gobo'}}}for(const p of portals){const q=Math.hypot(p.x-state.x,p.y-state.y);if(q<d){d=q;b={kind:'portal',o:p,label:'Vstopi: '+p.name}}}for(const site of exploreSites){const q=Math.hypot(site.x-state.x,site.y-state.y);if(q<d){d=q;b={kind:'site',o:site,label:(state.discoveries[site.id]?'Preglej: ':'Razišči: ')+site.name}}}if(Math.hypot(standard.x-state.x,standard.y-state.y)<d)b={kind:'standard',label:'Uporabi Zborni kol'};if(Math.hypot(perunShrine.x-state.x,perunShrine.y-state.y)<d)b={kind:'perun',label:'Dotakni se Perunovega oltarja'};if(Math.hypot(riverAltar.x-state.x,riverAltar.y-state.y)<d)b={kind:'river',label:'Položi daritev v reko'};target=b;ui.prompt.classList.toggle('show',!!b&&!dialogue&&!mapOpen&&!menuOpen);ui.prompt.innerHTML=b?'<b>E</b> · '+b.label:''}
function updateFx(dt){for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=120*dt;p.life-=dt}for(const f of floaters){f.y-=28*dt;f.life-=dt}for(let i=particles.length-1;i>=0;i--)if(particles[i].life<=0)particles.splice(i,1);for(let i=floaters.length-1;i>=0;i--)if(floaters[i].life<=0)floaters.splice(i,1);for(const o of resources)o.bump=Math.max(0,o.bump-dt*5)}
function questTarget(){switch(state.quest){case 0:return{x:npcs[0].x,y:npcs[0].y,label:'Pogovori se z Miro'};case 1:return{x:npcs[2].x,y:npcs[2].y,label:'Poišči generala Gruba'};case 2:return{x:npcs[3].x,y:npcs[3].y,label:'Poišči generala Niba'};case 3:return{x:78*T,y:24*T,label:'Zberi jagode in rudo'};case 4:return{x:npcs[0].x,y:npcs[0].y,label:'Vrni se k Miri'};case 5:return{x:standard.x,y:standard.y,label:'Obesi nevtralno praporje'};case 6:return{x:111*T,y:48*T,label:'Premagaj Bogluga'};case 7:return{x:npcs[0].x,y:npcs[0].y,label:'Poročaj Miri'};case 9:return{x:npcs[4].x,y:npcs[4].y,label:'Poišči Lado v Belem gaju'};case 10:return{x:165*T,y:38*T,label:'Naberi 6 mesečnic'};case 11:return{x:184*T,y:25*T,label:'Vstopi v Velesovo jamo'};case 12:return{x:npcs[4].x,y:npcs[4].y,label:'Vrni zvonček Ladi'};case 13:return{x:npcs[5].x,y:npcs[5].y,label:'Poišči kovača Bora'};case 14:return{x:82*T,y:20*T,label:'Zberi 5 rud in 3 zaponke'};case 15:return{x:npcs[5].x,y:npcs[5].y,label:'Vrni se h kovaču Boru'};case 16:return{x:npcs[6].x,y:npcs[6].y,label:'Poišči žreca Radovana'};case 17:return{x:perunShrine.x,y:perunShrine.y,label:'Prebudi Perunov oltar'};case 18:return{x:207*T,y:14*T,label:'Premagaj Gromovnika'};case 19:return{x:npcs[6].x,y:npcs[6].y,label:'Vrni se k Radovanu'};case 20:return{x:npcs[7].x,y:npcs[7].y,label:'Poišči mlinarja Jureta'};case 21:return{x:70*T,y:88*T,label:'Zberi 3 polena in 4 gobe'};case 22:return{x:riverAltar.x,y:riverAltar.y,label:'Prinesi daritev rečnemu oltarju'};case 23:return{x:60*T,y:111*T,label:'Premagaj Povodnega moža'};case 24:return{x:npcs[7].x,y:npcs[7].y,label:'Vrni se k mlinarju Juretu'};default:return{x:205*T,y:10*T,label:'Vstopi v kraljestvo Zlatoroga'}}}
function update(dt){if(state.hp>0){updatePlayer(dt);updateEnemies(dt);nearest()}updateFx(dt);time+=dt;saveClock+=dt;if(saveClock>9)save();if(time>weatherUntil)setWeather(Math.random()<.45?'sunny':Math.random()<.72?'cloudy':'rain',28+Math.random()*35);if(state.scene==='world'){camera.x+=(state.x-W/2-camera.x)*Math.min(1,dt*5);camera.y+=(state.y-H/2-camera.y)*Math.min(1,dt*5);camera.x=Math.max(0,Math.min(WW*T-W,camera.x));camera.y=Math.max(0,Math.min(WH*T-H,camera.y))}else camera.x=camera.y=0;shake=Math.max(0,shake-dt*25);const r=state.scene==='world'?biomeAt(state.x,state.y):state.scene==='velesCave'?'ruins':state.scene==='dwarfHall'?'mountain':'village';if(r!==currentRegion){currentRegion=r;ui.track.textContent=A.setRegion(r)}ui.location.textContent=state.scene==='world'?locationAt(state.x/T,state.y/T,r):portals.find(p=>p.id===state.scene)?.name||'Notranjost';const g=questTarget(),dist=state.scene==='world'?Math.round(Math.hypot(g.x-state.x,g.y-state.y)/T):0;ui.pin.textContent=g.label;ui.compass.textContent=state.scene==='world'?'Cilj: '+g.label+' · '+dist+' korakov':'Cilj: razišči prostor';const hour=Math.floor(((((state.playtime+time)%240)/240)*24+6)%24);ui.clock.textContent=(hour<6?'Noč':hour<10?'Jutro':hour<18?'Dan':hour<21?'Večer':'Noč')+' · '+String(hour).padStart(2,'0')+':00 · Samodejno shranjevanje'}
function regionName(r){return{village:'Jelševa vas',forest:'Veliki zeleni gozd',river:'Reka Šepetalka',mountain:'Sivi zobje',marsh:'Močvirje kresnic',goblin:'Goblinska meja',ruins:'Ruševine starega kralja'}[r]}
function locationAt(x,y,r){if(x>31&&x<58&&y>43&&y<64)return'Mesto Kresnikovo';if(x>142&&x<159&&y>44&&y<61)return'Brezovica';if(x>151&&x<188&&y>24&&y<57)return'Beli gaj vilincev';if(x>68&&x<98&&y<30)return'Matjaževo pod Peco';if(x>188&&y<35)return'Perunove ruševine';if(x>52&&x<73&&y>85)return'Polja ob Kolpi';if(x>24&&x<51&&y>61&&y<81)return'Zlata polja';return regionName(r)}
const sx=x=>Math.round(x-camera.x),sy=y=>Math.round(y-camera.y);
const visible=(x,y,margin=110)=>x>camera.x-margin&&x<camera.x+W+margin&&y>camera.y-margin&&y<camera.y+H+margin;
function tile(tx,ty){const x=tx*T-camera.x,y=ty*T-camera.y,b=biomeAt(tx*T,ty*T),n=rnd(tx,ty),path=pathTile(tx,ty);if(waterTile(tx,ty)){const riverDist=Math.abs(tx-riverCenter(ty)),edge=riverDist>1.15;X.fillStyle=edge?'#5f8982':'#31575f';X.fillRect(x,y,T+1,T+1);if(edge){X.fillStyle='#789b8d44';X.fillRect(x,y,T+1,T+1)}X.strokeStyle=edge?'#b0c4ad66':'#91aaa255';X.lineWidth=edge?1.5:1;const w=(time*(edge?5:11)+tx*11+ty*5)%40;X.beginPath();X.moveTo(x+w-12,y+9);X.lineTo(x+w+8,y+9);if(!edge){X.moveTo(x+30-w*.32,y+23);X.lineTo(x+42-w*.32,y+23)}X.stroke();return}const palettes={village:'#65734d',forest:'#4b6040',river:'#566d4d',mountain:'#6b7060',marsh:'#435748',goblin:'#656746',ruins:'#586154'},base=path?'#776c52':palettes[b];X.fillStyle=base;X.fillRect(x,y,T+1,T+1);if(path){X.fillStyle='#38342925';if(rnd(tx,ty,4)>.43){X.beginPath();X.ellipse(x+7+n*19,y+8+rnd(tx,ty,5)*17,2+n*3,1.3,0,0,7);X.fill()}if(weather==='rain'||weather==='storm'){X.fillStyle='#81908b32';X.beginPath();X.ellipse(x+9+n*13,y+22,5+n*3,2,0,0,7);X.fill()}}else{X.fillStyle=b==='mountain'?'#a3a58d3d':'#a8b67c35';if(rnd(tx,ty,2)>.65){X.beginPath();X.moveTo(x+6+rnd(tx,ty,3)*19,y+15);X.lineTo(x+8+rnd(tx,ty,3)*19,y+8);X.moveTo(x+9+rnd(tx,ty,6)*15,y+18);X.lineTo(x+11+rnd(tx,ty,6)*15,y+12);X.strokeStyle=X.fillStyle;X.lineWidth=1;X.stroke()}}}
function riverRibbon(y0,y1,half,color){const pts=[];for(let wy=y0;wy<=y1;wy+=12)pts.push([riverCenter(wy/T)*T-camera.x,wy-camera.y]);if(pts.length<2)return;X.beginPath();for(let i=0;i<pts.length;i++){const [cx,sy]=pts[i],px=cx-half;i?X.lineTo(px,sy):X.moveTo(px,sy)}for(let i=pts.length-1;i>=0;i--){const [cx,sy]=pts[i];X.lineTo(cx+half,sy)}X.closePath();X.fillStyle=color;X.fill()}
function drawHydrology(){if(state.scene!=='world')return;const minY=Math.max(32,camera.y-40),maxY=Math.min((WH-1)*T,camera.y+H+40);for(const [a,b] of[[T,47*T],[51*T,72*T],[76*T,(WH-1)*T]]){const y0=Math.max(a,minY),y1=Math.min(b,maxY);if(y1<=y0)continue;riverRibbon(y0,y1,73,'#668e86');riverRibbon(y0,y1,48,'#31575f');for(let wy=y0+18;wy<y1;wy+=46){const cx=riverCenter(wy/T)*T-camera.x,sy=wy-camera.y,drift=(time*12+wy*.17)%30;X.strokeStyle='#a9bbb055';X.lineWidth=1.5;X.beginPath();X.moveTo(cx-22+drift,sy);X.lineTo(cx-4+drift,sy);X.stroke()}}const lx=131*T-camera.x,ly=76*T-camera.y;if(lx>-400&&lx<W+400&&ly>-350&&ly<H+350){X.fillStyle='#668e86';X.beginPath();X.ellipse(lx,ly,13*T,11*T,0,0,7);X.fill();X.fillStyle='#31575f';X.beginPath();X.ellipse(lx,ly,10.8*T,8.8*T,0,0,7);X.fill();X.strokeStyle='#a9bbb044';for(let i=-6;i<=6;i+=2){X.beginPath();X.moveTo(lx-180+i*7,ly+i*21);X.lineTo(lx-135+i*7,ly+i*21);X.stroke()}}}
function shadow(x,y,w=22){X.fillStyle='#07100744';X.beginPath();X.ellipse(sx(x),sy(y)+12,w,7,0,0,7);X.fill()}
function atlasSprite(img,index,cols,rows,x,y,w,h,flip=false,pad=0){if(!img.complete||!img.naturalWidth)return false;const cellW=img.naturalWidth/cols,cellH=img.naturalHeight/rows,sw=cellW-pad*2,sh=cellH-pad*2,sxi=(index%cols)*cellW+pad,syi=Math.floor(index/cols)*cellH+pad;X.save();X.translate(x,y);if(flip)X.scale(-1,1);X.drawImage(img,sxi,syi,sw,sh,-w/2,-h,w,h);X.restore();return true}
function tree(o){const x=sx(o.x),y=sy(o.y),variant=rnd(o.x/T,o.y/T,7)>.48,wind=Math.sin(time*.8+o.x*.013)*.018+o.bump*.02;shadow(o.x,o.y,21);X.save();X.translate(x,y);X.rotate(wind);X.fillStyle='#493b2b';X.fillRect(-4,-35,8,39);if(!variant){for(const [dy,w] of[[-82,14],[-67,22],[-49,29],[-30,35]]){X.fillStyle='#314936';X.beginPath();X.moveTo(0,dy);X.lineTo(-w,dy+35);X.lineTo(w,dy+35);X.closePath();X.fill();X.fillStyle='#607a4e';X.beginPath();X.moveTo(-3,dy+5);X.lineTo(-w*.58,dy+29);X.lineTo(w*.2,dy+29);X.closePath();X.fill()}}else for(const [dx,dy,r] of[[0,-60,21],[-15,-46,17],[15,-45,18],[0,-31,21]]){X.fillStyle='#314936';X.beginPath();X.arc(dx,dy,r,0,7);X.fill();X.fillStyle='#6f8757';X.beginPath();X.arc(dx-4,dy-5,r*.58,0,7);X.fill()}X.restore()}
function rock(o){const x=sx(o.x),y=sy(o.y),ore=o.id.startsWith('ore');shadow(o.x,o.y,18);X.fillStyle=ore?'#565f5e':'#74796d';X.beginPath();X.moveTo(x-23,y+13);X.lineTo(x-18,y-6);X.lineTo(x-6,y-20);X.lineTo(x+10,y-16);X.lineTo(x+23,y-2);X.lineTo(x+18,y+14);X.closePath();X.fill();X.fillStyle='#a6aa98';X.beginPath();X.moveTo(x-15,y-5);X.lineTo(x-5,y-15);X.lineTo(x+8,y-12);X.lineTo(x+1,y-7);X.closePath();X.fill();X.fillStyle='#667b4d';X.beginPath();X.ellipse(x-11,y+7,9,4,-.2,0,7);X.fill();if(ore){X.strokeStyle='#708f99';X.lineWidth=3;X.beginPath();X.moveTo(x+8,y-12);X.lineTo(x+2,y-3);X.lineTo(x+9,y+9);X.stroke()}}
function forage(o){const x=sx(o.x),y=sy(o.y);if(o.type==='berry'){X.fillStyle='#2a5735';X.fillRect(x-9,y,18,11);X.fillStyle='#6658ad';X.fillRect(x-7,y-4,5,5);X.fillRect(x+2,y-7,5,5);X.fillRect(x+6,y+1,4,4)}else if(o.type==='flower'){X.strokeStyle='#b7c7a6';X.lineWidth=2;X.beginPath();X.moveTo(x,y+8);X.lineTo(x,y-2);X.stroke();X.fillStyle='#d8e4ee';for(let i=0;i<5;i++){X.beginPath();X.arc(x+Math.cos(i*1.256)*5,y-5+Math.sin(i*1.256)*5,3,0,7);X.fill()}X.fillStyle='#e9c96a';X.fillRect(x-2,y-7,4,4)}else{X.fillStyle='#dfd1a5';X.fillRect(x-2,y,4,9);X.fillStyle='#c45b45';X.beginPath();X.arc(x,y,7+Math.sin(time*2+o.x)*.5,Math.PI,Math.PI*2);X.fill();X.fillStyle='#f2bd76';X.fillRect(x-3,y-5,2,2)}}
function person(x,y,body,hair,walk=0,dir=0,goblin=false,anim=null){const px=sx(x),py=sy(y),stride=Math.sin(walk),bob=Math.abs(stride)*-1.4,dwarf=body==='#72533d';shadow(x,y,goblin?10:8);X.save();X.translate(px,py+bob);const skin=goblin?'#758851':'#b98762',torso=dwarf?14:11;X.strokeStyle='#292820';X.lineWidth=3;X.beginPath();X.moveTo(-3,8);X.lineTo(-4-stride*3,22);X.moveTo(3,8);X.lineTo(4+stride*3,22);X.stroke();X.fillStyle=body;X.beginPath();X.moveTo(-torso/2,-9);X.lineTo(torso/2,-9);X.lineTo(torso/2+2,9);X.lineTo(-torso/2-2,9);X.closePath();X.fill();X.strokeStyle='#1c211b55';X.stroke();X.fillStyle=skin;X.beginPath();X.ellipse(0,-16,goblin?6:5,goblin?6:7,0,0,7);X.fill();if(goblin){X.beginPath();X.moveTo(-5,-17);X.lineTo(-10,-15);X.lineTo(-5,-13);X.fill();X.beginPath();X.moveTo(5,-17);X.lineTo(10,-15);X.lineTo(5,-13);X.fill()}X.fillStyle=hair;X.beginPath();X.arc(0,-19,6,Math.PI,Math.PI*2);X.fill();X.fillStyle='#1a1c17';X.fillRect(Math.cos(dir)>0?2:-3,-17,1.5,1.5);const arm=stride*4;X.strokeStyle=skin;X.lineWidth=2.5;X.beginPath();X.moveTo(-5,-5);X.lineTo(-7+arm,7);X.moveTo(5,-5);X.lineTo(7-arm,7);X.stroke();if(anim)drawTool(anim,dir);X.restore()}
function drawArin(x,y,walk,dir,anim){person(x,y,'#496b58','#4b3428',walk,dir,false,anim)}
function drawTool(anim,dir){const p=Math.max(0,Math.min(1,anim.progress||0)),smooth=t=>t*t*(3-2*t);let swing;if(p<.24)swing=-1.25-smooth(p/.24)*.42;else if(p<.62)swing=-1.67+smooth((p-.24)/.38)*2.55;else swing=.88-smooth((p-.62)/.38)*.62;const heavy=anim.type==='chop'||anim.type==='mine',angle=dir+swing*(heavy?1.08:1);X.save();X.rotate(angle);X.translate(1,-2);X.fillStyle='#b98762';X.beginPath();X.arc(7,0,3.4,0,7);X.arc(16,0,3.1,0,7);X.fill();X.strokeStyle='#8f6840';X.lineWidth=3;X.beginPath();X.moveTo(5,0);X.lineTo(28,0);X.stroke();if(anim.type==='chop'){X.fillStyle='#b9c1bb';X.beginPath();X.moveTo(25,-10);X.lineTo(34,-7);X.lineTo(31,9);X.lineTo(25,6);X.closePath();X.fill()}else if(anim.type==='mine'){X.strokeStyle='#b7c0bb';X.lineWidth=4;X.beginPath();X.moveTo(23,-10);X.quadraticCurveTo(32,0,23,10);X.stroke()}else{const blade=items[state.weapon]||items.sword;X.strokeStyle=blade===items.goldScimitar?'#f1cc57':'#d8ded6';X.lineWidth=4;X.beginPath();X.moveTo(26,0);if(blade.scimitar){X.quadraticCurveTo(40,8,46,-5);X.quadraticCurveTo(43,8,31,5)}else X.lineTo(45,0);X.stroke();X.fillStyle='#c5a85d';X.fillRect(23,-6,3,12)}X.restore()}
function goblinEnemy(e){const p=e.attack>.75?{type:'attack',progress:(1.15-e.attack)/.4}:null;person(e.x,e.y,e.type==='boss'?'#6b4130':'#665638','#302a1d',time*5+e.phase,Math.atan2(state.y-e.y,state.x-e.x),true,p);const x=sx(e.x),y=sy(e.y);if(e.type==='boss'){X.fillStyle='#a9513c';X.fillRect(x-18,y-27,36,6)}if(e.hp<e.max){X.fillStyle='#151915';X.fillRect(x-18,y-32,36,4);X.fillStyle='#c3594f';X.fillRect(x-18,y-32,36*e.hp/e.max,4)}}
function creature(e){if(e.type==='goblin'||e.type==='boss'){goblinEnemy(e);return}const x=sx(e.x),y=sy(e.y),p=Math.sin(time*4+e.phase);shadow(e.x,e.y,e.type.includes('Troll')?23:14);X.save();if(e.hit)X.globalAlpha=.55;if(e.type.includes('Troll')){const cave=e.type==='caveTroll',river=e.type==='riverTroll';X.fillStyle=cave?'#9a988a':river?'#536d63':'#66704d';X.beginPath();X.ellipse(x,y-2,22+p*.6,28,0,0,7);X.fill();X.fillStyle='#3e3a31';X.fillRect(x-16,y+14,9,17);X.fillRect(x+7,y+14,9,17);X.fillStyle=cave?'#d4d0ba':'#81745c';X.beginPath();X.ellipse(x,y-24,15,13,0,0,7);X.fill();X.fillStyle='#211f1b';X.fillRect(x-7,y-27,3,3);X.fillRect(x+5,y-27,3,3);X.strokeStyle='#493826';X.lineWidth=6;X.beginPath();X.moveTo(x-18,y-8);X.lineTo(x-29,y+14);X.moveTo(x+18,y-8);X.lineTo(x+29,y+14);X.stroke()}else if(e.type==='deer'){X.fillStyle='#876947';X.beginPath();X.ellipse(x,y,18,10,0,0,7);X.fill();X.fillRect(x+12,y-11,8,13);X.fillStyle='#d7c49d';X.fillRect(x+17,y-10,2,2);X.strokeStyle='#4b3827';X.lineWidth=2;X.beginPath();X.moveTo(x-10,y+7);X.lineTo(x-12,y+19);X.moveTo(x+9,y+7);X.lineTo(x+11,y+19);X.moveTo(x+16,y-10);X.lineTo(x+12,y-20);X.moveTo(x+17,y-11);X.lineTo(x+22,y-20);X.stroke()}else if(e.type==='chicken'){X.fillStyle='#d4c7a4';X.beginPath();X.ellipse(x,y+4,8,7,0,0,7);X.fill();X.fillStyle='#a84c3d';X.fillRect(x+4,y-6,4,5);X.fillStyle='#d2a34f';X.fillRect(x+7,y,5,2)}else if(e.type==='slime'){X.fillStyle='#6fa24b';X.beginPath();X.ellipse(x,y+3,16+p,13-p*.5,0,Math.PI,0);X.lineTo(x+16,y+11);X.lineTo(x-16,y+11);X.fill();X.fillStyle='#172014';X.fillRect(x-7,y,3,3);X.fillRect(x+5,y,3,3)}else{X.fillStyle='#555f55';X.fillRect(x-14,y-7,27,16);X.fillStyle='#737d6f';X.fillRect(x+8,y-12,14,12);X.fillStyle='#d1c090';X.fillRect(x+18,y-10,2,2);X.fillStyle='#343a33';X.fillRect(x-12,y+8,5,9);X.fillRect(x+6,y+8,5,9)}X.restore();if(!e.passive&&e.hp<e.max){X.fillStyle='#171b17';X.fillRect(x-20,y-38,40,4);X.fillStyle='#c45b4f';X.fillRect(x-20,y-38,40*e.hp/e.max,4)}}
function house(tx,ty,roof='#56392b',kind=0){const x=sx(tx*T),y=sy(ty*T),w=kind===2?82:74,h=kind===1?56:50;shadow(tx*T,ty*T,w*.48);X.fillStyle='#6b6a5d';X.fillRect(x-w/2-3,y-h/2,w+6,h/2+25);X.fillStyle=kind===1?'#c1ae86':kind===2?'#a89168':'#d0bd94';X.fillRect(x-w/2,y-h/2-7,w,h);X.strokeStyle='#503d2b';X.lineWidth=3;X.strokeRect(x-w/2,y-h/2-7,w,h);X.beginPath();X.moveTo(x-w/2+11,y-h/2-7);X.lineTo(x-w/2+11,y+h/2-7);X.moveTo(x+w/2-11,y-h/2-7);X.lineTo(x+w/2-11,y+h/2-7);X.moveTo(x-w/2,y-4);X.lineTo(x+w/2,y-4);X.stroke();X.fillStyle=roof;X.beginPath();X.moveTo(x-w/2-8,y-h/2-8);X.lineTo(x,y-h-24);X.lineTo(x+w/2+8,y-h/2-8);X.lineTo(x+w/2,y-h/2+1);X.lineTo(x,y-h-13);X.lineTo(x-w/2,y-h/2+1);X.closePath();X.fill();X.strokeStyle='#2f291f';X.lineWidth=2;X.stroke();X.strokeStyle='#94735666';X.lineWidth=1;for(let i=-w/2+6;i<w/2;i+=8){X.beginPath();X.moveTo(x,y-h-21);X.lineTo(x+i,y-h/2-4);X.stroke()}X.fillStyle='#493426';X.fillRect(x-7,y+4,14,20);X.fillStyle='#8db0a4';for(const dx of[-w/2+17,w/2-25]){X.fillRect(x+dx,y-h/2+3,9,9);X.strokeStyle='#34443f';X.strokeRect(x+dx,y-h/2+3,9,9);X.beginPath();X.moveTo(x+dx+4.5,y-h/2+3);X.lineTo(x+dx+4.5,y-h/2+12);X.stroke()}if(kind===1){X.fillStyle='#4c4233';X.fillRect(x+w/2-13,y-h-28,8,20);X.fillStyle='#e59a45aa';X.fillRect(x+w/2+5,y-5,4,5)}if(kind===2){X.fillStyle='#6e3e32';X.fillRect(x-w/2-6,y+3,18,7);X.fillStyle='#d8bd75';X.fillRect(x-w/2-2,y+5,10,3)}}
function hayrack(tx,ty){const x=sx(tx*T),y=sy(ty*T);shadow(tx*T,ty*T,48);X.strokeStyle='#4b3c2b';X.lineWidth=6;X.beginPath();X.moveTo(x-38,y+22);X.lineTo(x-34,y-37);X.moveTo(x+38,y+22);X.lineTo(x+34,y-37);X.stroke();X.lineWidth=3;for(let i=-26;i<28;i+=10){X.beginPath();X.moveTo(x-32,y+i);X.lineTo(x+32,y+i);X.stroke()}X.fillStyle='#4a3a29';X.beginPath();X.moveTo(x-48,y-35);X.lineTo(x,y-58);X.lineTo(x+48,y-35);X.lineTo(x+40,y-27);X.lineTo(x,y-46);X.lineTo(x-40,y-27);X.closePath();X.fill();X.fillStyle='#a58b4f';X.fillRect(x-29,y-5,58,13)}
function well(tx,ty){const x=sx(tx*T),y=sy(ty*T);shadow(tx*T,ty*T,18);X.fillStyle='#686a5d';X.beginPath();X.ellipse(x,y+5,20,9,0,0,7);X.fill();X.fillStyle='#222d2d';X.beginPath();X.ellipse(x,y+2,13,5,0,0,7);X.fill();X.strokeStyle='#58412d';X.lineWidth=4;X.beginPath();X.moveTo(x-17,y+1);X.lineTo(x-17,y-25);X.moveTo(x+17,y+1);X.lineTo(x+17,y-25);X.moveTo(x-20,y-24);X.lineTo(x+20,y-24);X.stroke()}
function stall(tx,ty,color){const x=sx(tx*T),y=sy(ty*T);X.fillStyle='#5a422e';X.fillRect(x-22,y-3,44,17);X.fillStyle=color;X.fillRect(x-25,y-21,50,13);X.fillStyle='#d0b56c';for(let i=-18;i<20;i+=12)X.fillRect(x+i,y+1,7,5)}
function exploreProp(o){if(!visible(o.x,o.y,70))return;const x=sx(o.x),y=sy(o.y),seen=state.discoveries[o.id];X.save();X.strokeStyle='#302c22';X.lineWidth=3;X.fillStyle='#71694f';if(o.type==='camp'||o.type==='fire'){X.fillStyle='#4b3828';X.beginPath();X.ellipse(x,y+5,22,8,0,0,7);X.fill();for(let i=-1;i<=1;i++){X.strokeStyle='#6d4b30';X.beginPath();X.moveTo(x-15,y+6+i*3);X.lineTo(x+15,y+i*3);X.stroke()}if(!seen){X.fillStyle='#d57d38';X.beginPath();X.moveTo(x,y+3);X.quadraticCurveTo(x-8,y-9,x,y-20);X.quadraticCurveTo(x+10,y-7,x,y+3);X.fill()}}else if(o.type==='shrine'||o.type==='idol'){X.fillStyle='#696d60';X.fillRect(x-10,y-25,20,31);X.fillStyle='#98987c';X.fillRect(x-6,y-20,12,7);X.strokeStyle='#36382f';X.beginPath();X.moveTo(x-4,y-13);X.lineTo(x+4,y-7);X.moveTo(x+4,y-13);X.lineTo(x-4,y-7);X.stroke()}else if(o.type==='stones'||o.type==='bones'){for(let i=0;i<3;i++){const a=i*2.1;X.fillStyle=i===1?'#8a8977':'#6f7467';X.beginPath();X.ellipse(x+Math.cos(a)*17,y+Math.sin(a)*7-8,7,15,Math.sin(a)*.2,0,7);X.fill()}}else if(o.type==='wreck'){X.strokeStyle='#61452e';X.lineWidth=5;X.strokeRect(x-20,y-15,33,18);X.beginPath();X.arc(x-16,y+7,7,0,7);X.arc(x+12,y+7,7,0,7);X.stroke()}else if(o.type==='apiary'){for(let i=0;i<3;i++){X.fillStyle=i%2?'#8b6d36':'#a18443';X.fillRect(x-19+i*13,y-18,10,23)}X.fillStyle='#523b27';X.fillRect(x-23,y+5,45,5)}else if(o.type==='hut'){X.fillStyle='#6f5538';X.fillRect(x-20,y-18,40,25);X.fillStyle='#493727';X.beginPath();X.moveTo(x-25,y-17);X.lineTo(x,y-38);X.lineTo(x+25,y-17);X.fill()}else if(o.type==='tower'){X.strokeStyle='#59432e';X.lineWidth=5;X.beginPath();X.moveTo(x-14,y+10);X.lineTo(x-9,y-32);X.moveTo(x+14,y+10);X.lineTo(x+9,y-32);X.moveTo(x-14,y-14);X.lineTo(x+14,y-14);X.stroke();X.fillStyle='#665039';X.fillRect(x-17,y-37,34,8)}if(!seen){const glow=.55+.4*Math.sin(time*3+o.x);X.fillStyle=`rgba(238,207,105,${glow})`;X.beginPath();X.arc(x,y-43,3,0,7);X.fill();X.strokeStyle='#ecd98b88';X.lineWidth=1;X.beginPath();X.moveTo(x-7,y-43);X.lineTo(x+7,y-43);X.moveTo(x,y-50);X.lineTo(x,y-36);X.stroke()}X.restore()}
function props(){for(let fy=64;fy<78;fy+=3){X.strokeStyle='#aa955555';X.lineWidth=2;X.beginPath();X.moveTo(sx(26*T),sy(fy*T));X.lineTo(sx(48*T),sy(fy*T));X.stroke();for(let fx=27;fx<48;fx+=2){X.fillStyle='#c6aa56';X.fillRect(sx(fx*T),sy(fy*T)-5,2,7)}}house(13,47);house(23,48,'#443326');house(18,57,'#34412b');hayrack(28,59);const city=cityPlots;for(const h of city)house(h[0],h[1],h[2],h[3]);well(45,53);stall(40,53,'#6f4035');stall(46,57,'#596c43');stall(51,52,'#77633f');house(145,47,'#3c3529');house(153,46,'#453629');house(157,56,'#39402f');hayrack(146,58);house(82,17,'#424843');house(172,32,'#4b5940');house(61,92,'#59412d');house(194,19,'#45444c');for(const c of [[96,42,'#913c31'],[103,40,'#913c31'],[115,55,'#405c8d'],[122,53,'#405c8d']]){const x=sx(c[0]*T),y=sy(c[1]*T);X.fillStyle='#6b4930';X.beginPath();X.moveTo(x-18,y+15);X.lineTo(x,y-18);X.lineTo(x+18,y+15);X.fill();X.strokeStyle=c[2];X.lineWidth=4;X.stroke()}let x=sx(standard.x),y=sy(standard.y);X.fillStyle='#5f452a';X.fillRect(x-3,y-25,6,43);X.fillStyle=state.quest===5?'#b9ac7d':'#6d5a3d';X.fillRect(x+3,y-22,25,15);for(const altar of [perunShrine,riverAltar]){x=sx(altar.x),y=sy(altar.y);X.fillStyle='#6b7168';X.fillRect(x-15,y-9,30,18);X.fillStyle=altar===perunShrine?'#d6c471':'#5f9995';X.fillRect(x-4,y-17,8,9)}}
function drawInterior(){X.clearRect(0,0,W,H);const cave=['velesCave','kresnikSewer','matjazCave','ajdTomb','trollMine','vilenica'].includes(state.scene),dwarf=state.scene==='dwarfHall'||state.scene==='trollMine',royal=state.scene==='matjazCave';X.fillStyle=cave?(royal?'#17191d':'#151b19'):dwarf?'#303733':'#443b2b';X.fillRect(0,0,W,H);X.fillStyle=cave?(royal?'#30333a':'#252d2b'):dwarf?'#515a52':'#76674a';for(let y=72;y<H-50;y+=32)for(let x=48;x<W-48;x+=32)X.fillRect(x,y,30,30);X.fillStyle='#111511';X.fillRect(0,0,W,72);X.fillRect(0,H-50,W,50);X.fillStyle='#6a4c2e';X.fillRect(W/2-34,H-58,68,16);X.fillStyle=state.chests[state.scene]?'#4b3a28':'#8b6334';X.fillRect(W/2+115,H/2-15,40,30);X.fillStyle='#d5b261';X.fillRect(W/2+130,H/2-15,6,30);if(cave){X.fillStyle=state.scene==='vilenica'?'#91b4aa':'#5f8178';for(let i=0;i<14;i++)X.fillRect(90+i*59,95+(i%3)*110,3,13);if(royal){X.fillStyle='#786c50';X.fillRect(W/2-95,H/2-38,190,76);X.fillStyle='#a79a73';X.beginPath();X.ellipse(W/2,H/2,75,27,0,0,7);X.fill()}}else{X.fillStyle='#d7b359';X.fillRect(180,130,8,45);X.fillRect(770,130,8,45)}drawInteriorDetails();let anim=null;if(player.action)anim={type:player.action.type,progress:player.action.t/player.action.total};else if(player.attack)anim={type:'attack',progress:1-player.attack/.23};drawArin(state.x,state.y,player.walk,state.dir,anim)}
function drawInteriorDetails(){const id=state.scene;X.save();if(['velesCave','kresnikSewer','matjazCave','ajdTomb','trollMine','vilenica'].includes(id)){X.strokeStyle=id==='vilenica'?'#72a89a88':'#4d776d66';X.lineWidth=3;for(let i=0;i<6;i++){const x=115+i*137,y=155+(i%2)*190;X.beginPath();X.moveTo(x,y+22);X.lineTo(x-9,y+43);X.lineTo(x+8,y+43);X.stroke()}if(id==='trollMine'){X.strokeStyle='#8b7451';X.lineWidth=4;X.beginPath();X.moveTo(90,440);X.lineTo(870,440);X.moveTo(90,470);X.lineTo(870,470);X.stroke();for(let x=110;x<870;x+=55){X.beginPath();X.moveTo(x,430);X.lineTo(x,480);X.stroke()}}if(id==='kresnikSewer'){X.fillStyle='#294843';X.fillRect(60,245,840,74);X.strokeStyle='#6b9187';for(let x=70;x<900;x+=54){X.beginPath();X.moveTo(x,270);X.lineTo(x+30,270);X.stroke()}}if(id==='matjazCave'){X.fillStyle='#8e845f';X.fillRect(375,210,210,35);X.fillStyle='#d6c078';X.font='18px Georgia';X.textAlign='center';X.fillText('KRALJ SPI, DOKLER BRADA NE OVije MIZE',480,185)}if(id==='ajdTomb'){X.fillStyle='#716b58';for(const x of[150,300,660,810]){X.beginPath();X.moveTo(x,340);X.lineTo(x-28,395);X.lineTo(x+28,395);X.closePath();X.fill()}}}else{X.fillStyle='#423526';for(const x of[120,270,690,840])X.fillRect(x,170,74,38);X.fillStyle='#c99749';for(const x of[155,805]){X.beginPath();X.arc(x,140,5+Math.sin(time*5)*2,0,7);X.fill()}if(id==='kresnikForge'){X.fillStyle='#d66d32';X.fillRect(705,135,75,42);X.fillStyle='#282a26';X.fillRect(260,300,95,28)}if(id==='kresnikInn'){X.fillStyle='#6b4b31';for(let y=270;y<420;y+=75)for(let x=130;x<850;x+=180)X.fillRect(x,y,75,34)}}X.restore()}
function drawWeather(){if(weather==='sunny'){const g=X.createLinearGradient(0,0,W,H);g.addColorStop(0,'#ead49a15');g.addColorStop(.55,'transparent');X.fillStyle=g;X.fillRect(0,0,W,H)}if(weather==='cloudy'||weather==='rain'||weather==='storm'){const drift=(time*11)%1500,g=X.createRadialGradient(drift-220,170,20,drift-220,170,420);g.addColorStop(0,weather==='storm'?'#27322d66':'#26322842');g.addColorStop(1,'transparent');X.fillStyle=g;X.fillRect(0,0,W,H)}if(state.settings.weatherFx&&(weather==='rain'||weather==='storm')){const count=weather==='storm'?75:34;X.lineCap='round';for(let i=0;i<count;i++){const depth=.35+((i*37)%65)/100,x=(i*137+time*(230+depth*260))%(W+80)-40,y=(i*83+time*(360+depth*410))%(H+60)-30;X.strokeStyle=`rgba(185,205,200,${.08+depth*.22})`;X.lineWidth=depth*1.4;X.beginPath();X.moveTo(x,y);X.lineTo(x-4*depth,y+11*depth);X.stroke();if(y>H-45&&i%6===0){X.strokeStyle='#c1d1cb45';X.beginPath();X.ellipse(x,y,7*depth,2*depth,0,0,7);X.stroke()}}}if(weather==='storm'&&Math.sin(time*3.7)>.992){X.fillStyle='#dce6df52';X.fillRect(0,0,W,H)}}
function drawDayNight(){}
function drawWorld(){if(state.scene!=='world'){drawInterior();drawWeather();return}const jx=state.settings.screenShake&&shake?(Math.random()-.5)*shake:0,jy=state.settings.screenShake&&shake?(Math.random()-.5)*shake:0;X.clearRect(0,0,W,H);X.save();X.translate(jx,jy);for(let y=Math.floor(camera.y/T);y<=Math.ceil((camera.y+H)/T);y++)for(let x=Math.floor(camera.x/T);x<=Math.ceil((camera.x+W)/T);x++)tile(x,y);drawHydrology();props();const list=[];for(const o of resources)if(!state.harvested[o.id]&&visible(o.x,o.y,130))list.push({y:o.y,fn:()=>o.type==='tree'?tree(o):o.type==='rock'?rock(o):forage(o)});for(const n of npcs)if(visible(n.x,n.y,90))list.push({y:n.y,fn:()=>{if(n.troll)creature({type:'mountainTroll',x:n.x,y:n.y,phase:0,hit:0,hp:1,max:1});else person(n.x,n.y,n.body,n.hair,0,0,n.goblin);if(Math.hypot(n.x-state.x,n.y-state.y)<145){X.fillStyle='#f0dfad';X.font='11px Georgia';X.textAlign='center';X.fillText(n.name,sx(n.x),sy(n.y)-(n.troll?42:29))}}});for(const e of enemies)if(!e.dead&&visible(e.x,e.y,90))list.push({y:e.y,fn:()=>creature(e)});list.push({y:state.y,fn:()=>{if(player.invuln&&Math.floor(player.invuln*12)%2)return;let anim=null;if(player.action)anim={type:player.action.type,progress:player.action.t/player.action.total};else if(player.attack)anim={type:'attack',progress:1-player.attack/.23};drawArin(state.x,state.y,player.walk,state.dir,anim)}});list.sort((a,b)=>a.y-b.y).forEach(v=>v.fn());
  const g=questTarget(),gx=sx(g.x),gy=sy(g.y);if(gx>10&&gx<W-10&&gy>10&&gy<H-10){X.fillStyle='#e7c351';X.beginPath();X.moveTo(gx,gy-35+Math.sin(time*4)*3);X.lineTo(gx-6,gy-45+Math.sin(time*4)*3);X.lineTo(gx+6,gy-45+Math.sin(time*4)*3);X.fill()}
  for(const f of fireflies){const a=.2+.6*(Math.sin(time*2+f.p)*.5+.5),x=sx(f.x+Math.sin(time+f.p)*f.s),y=sy(f.y+Math.cos(time*.8+f.p)*f.s);if(x>0&&x<W&&y>0&&y<H){X.fillStyle=`rgba(239,211,105,${a})`;X.fillRect(x,y,2,2)}}for(const p of particles){X.globalAlpha=Math.max(0,p.life);X.fillStyle=p.color;X.fillRect(sx(p.x),sy(p.y),p.size,p.size)}X.globalAlpha=1;for(const f of floaters){X.globalAlpha=Math.max(0,f.life);X.fillStyle=f.color;X.font='bold 12px Georgia';X.textAlign='center';X.fillText(f.s,sx(f.x),sy(f.y))}X.globalAlpha=1;X.restore();drawWeather();drawDayNight()}
const quests={0:['Tri barve prepira','V Jelševi vasi te išče starešina Mira.',['Pogovori se z Miro']],1:['Tri barve prepira','Mira želi ustaviti goblinski spor, preden doseže vas.',['Prečkaj reko po kamnitem mostu','Poišči Rdeči tabor','Govori z generalom Grubom']],2:['Tri barve prepira','Grub zahteva barvo, boljšo od rdeče in modre.',['Poišči Modri tabor','Govori z generalom Nibom']],3:['Tri barve prepira','Mira potrebuje naravna barvila in mineralni sijaj.',['Zberi 5 mrakovih jagod','Izkoplji 3 kose modre rude']],4:['Tri barve prepira','Vse sestavine so zbrane.',['Vrni se k Miri']],5:['Tri barve prepira','Nevtralno praporje mora viseti med obema taboroma.',['Poišči Zborni kol','Obesi praporje']],6:['Tri barve prepira','Praporje je privabilo lačnega Bogluga.',['Premagaj Bogluga']],7:['Tri barve prepira','Prepir je končan na nenavaden način.',['Vrni se k Miri']],8:['Tri barve prepira','Goblini so pozabili, zakaj so bili jezni.',['Naloga opravljena']],9:['Srebrni glas Zlatoroga','V Belem gaju na vzhodu te čaka vilinka Lada.',['Poišči Lado']],10:['Srebrni glas Zlatoroga','Mesečnice razkrivajo skrite Velesove poti.',['Naberi 6 mesečnic']],11:['Srebrni glas Zlatoroga','Cvetlice kažejo k črni pečini.',['Vstopi v Velesovo jamo','Poišči srebrni zvonček']],12:['Srebrni glas Zlatoroga','Zvonček spet poje.',['Vrni se k Ladi']],13:['Velesova senca','Škrati v Sivih zobeh potrebujejo pomoč.',['Poišči kovača Bora']],14:['Velesova senca','Bor potrebuje kovino in goblinske zaponke.',['Zberi 5 modrih rud','Zberi 3 goblinske zaponke']],15:['Velesova senca','Material za črno rezilo je pripravljen.',['Vrni se h kovaču Boru']],16:['Perunov ukradeni grom','V ruševinah na vzhodu čaka žrec Radovan.',['Poišči žreca Radovana']],17:['Perunov ukradeni grom','Perunov oltar molči na severovzhodnem robu.',['Dotakni se Perunovega oltarja']],18:['Perunov ukradeni grom','Nevihta je prebudila Gromovnika.',['Premagaj Gromovnika']],19:['Perunov ukradeni grom','Grom se je vrnil v nebo.',['Vrni se k Radovanu']],20:['Nevesta iz globine','Mlinar Jure ob južni reki potrebuje pomoč.',['Poišči mlinarja Jureta']],21:['Nevesta iz globine','Reka zahteva dar življenja in ognja.',['Zberi 3 polena','Zberi 4 žerjavne gobe']],22:['Nevesta iz globine','Daritev je pripravljena.',['Poišči rečni oltar južno od mlina']],23:['Nevesta iz globine','Povodni mož preizkuša tvoj namen.',['Premagaj Povodnega moža']],24:['Nevesta iz globine','Reka je sprejela mir.',['Vrni se k mlinarju Juretu']],25:['Kraljestvo Zlatoroga','Pet zgodb je odprlo pot pod Triglav.',['Razišči odprto kraljestvo','Dosezi 15. raven za zmajski meč']]};
function objectiveDone(i){if(state.quest===3)return i===0?state.inventory.berry>=5:state.inventory.ore>=3;if(state.quest===10)return state.inventory.flower>=6;if(state.quest===14)return i===0?state.inventory.ore>=5:state.inventory.scrap>=3;if(state.quest===21)return i===0?state.inventory.wood>=3:state.inventory.mushroom>=4;return state.quest===8}
function updateUI(){ui.hp.style.width=100*state.hp/state.maxHp+'%';ui.hpText.value=Math.ceil(state.hp)+' / '+state.maxHp;const prev=45*(state.level-1)*(state.level-1),next=45*state.level*state.level;ui.xp.style.width=100*(state.xp-prev)/(next-prev)+'%';ui.xpText.value=state.xp+' / '+next;ui.level.textContent=state.level;ui.coins.textContent='● '+state.inventory.coin;const keys=Object.keys(items).filter(k=>(state.inventory[k]||0)>0),slots=20;ui.inventory.innerHTML=Array.from({length:slots},(_,i)=>{const k=keys[i];if(!k)return'<div class="slot"></div>';const d=items[k],n=state.inventory[k]||0;return`<button class="slot ${selectedItem===k?'selected':''} ${state.weapon===k?'equipped':''}" data-item="${k}" aria-label="${d.name}: ${n}">${d.icon}${n>1?`<small>${n}</small>`:''}${d.rare?'<i class="rare"></i>':''}</button>`}).join('');ui.inventory.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>selectItem(b.dataset.item));ui.skills.innerHTML=Object.entries(state.skills).map(([k,v])=>{const l=1+Math.floor(Math.sqrt(v/25)),a=25*(l-1)*(l-1),z=25*l*l;return`<div class="skill-row"><div><span>${skillNames[k]}</span><b>${l}. raven</b></div><div class="mini-meter"><i style="width:${100*(v-a)/(z-a)}%"></i></div></div>`}).join('');const q=quests[state.quest]||quests[25];let objectives=q[2];if(state.quest===3)objectives=[`Zberi 5 mrakovih jagod (${Math.min(5,state.inventory.berry)}/5)`,`Izkoplji 3 rude (${Math.min(3,state.inventory.ore)}/3)`];if(state.quest===10)objectives=[`Naberi 6 mesečnic (${Math.min(6,state.inventory.flower)}/6)`];if(state.quest===14)objectives=[`Zberi 5 rud (${Math.min(5,state.inventory.ore)}/5)`,`Zberi 3 zaponke (${Math.min(3,state.inventory.scrap)}/3)`];if(state.quest===21)objectives=[`Zberi 3 polena (${Math.min(3,state.inventory.wood)}/3)`,`Zberi 4 gobe (${Math.min(4,state.inventory.mushroom)}/4)`];ui.qTitle.textContent=q[0];ui.qText.textContent=q[1];ui.objectives.innerHTML=objectives.map((o,i)=>`<div class="objective ${objectiveDone(i)?'done':(!objectiveDone(0)&&i===0)||(objectiveDone(0)&&i===1)?'active':''}">${o}</div>`).join('');if(selectedItem&&state.inventory[selectedItem])selectItem(selectedItem,true)}
function selectItem(k,quiet=false){selectedItem=k;const d=items[k],n=state.inventory[k]||0,canEquip=d.weapon&&state.level>=d.level;ui.detail.innerHTML=`${d.use&&n?'<button id="useItem">Uporabi</button>':''}${d.weapon?`<button id="equipItem">${state.weapon===k?'Opremljeno':canEquip?'Opremi':'Raven '+d.level}</button>`:''}<span>${d.name} · ${n}</span><small>${d.desc}</small>`;if(d.use&&n)$('useItem').onclick=useMushroom;if(d.weapon)$('equipItem').onclick=()=>{if(!canEquip){notify('Potrebuješ '+d.level+'. bojno raven.');return}state.weapon=k;A.play('ui');notify('Opremljeno: '+d.name);updateUI();save()};if(!quiet)updateUI()}
function drawMap(){const w=MC.width,h=MC.height,sx=w/WW,sy=h/WH;MX.fillStyle='#b7a674';MX.fillRect(0,0,w,h);for(let y=0;y<WH;y+=2)for(let x=0;x<WW;x+=2){const b=biomeAt(x*T,y*T);MX.fillStyle=waterTile(x,y)?'#527b78':b==='mountain'?'#777a6c':b==='marsh'?'#53664d':b==='goblin'?'#777245':b==='ruins'?'#5f6656':'#617b4f';MX.fillRect(x*sx,y*sy,2*sx+1,2*sy+1)}MX.fillStyle='#9b865d';for(let y=0;y<WH;y++)for(let x=0;x<WW;x++)if(pathTile(x,y))MX.fillRect(x*sx,y*sy,Math.max(1,sx),Math.max(1,sy));for(const l of landmarks){MX.fillStyle=l.type==='danger'?'#923e38':'#754c31';MX.fillRect(l.x*sx-3,l.y*sy-3,7,7);MX.fillStyle='#302a22';MX.font='10px Georgia';MX.fillText(l.name,l.x*sx+6,l.y*sy+3)}const g=questTarget();MX.fillStyle='#e4bd52';MX.beginPath();MX.arc(g.x/T*sx,g.y/T*sy,6+Math.sin(time*4),0,7);MX.fill();MX.fillStyle='#f5f0dd';MX.beginPath();MX.arc(state.x/T*sx,state.y/T*sy,5,0,7);MX.fill()}
function drawMinimap(){const w=MMC.width,h=MMC.height,cx=w/2,cy=h/2,scale=7,range=14,ptx=state.x/T,pty=state.y/T;MMX.clearRect(0,0,w,h);MMX.save();MMX.beginPath();MMX.arc(cx,cy,88,0,Math.PI*2);MMX.clip();MMX.fillStyle='#536b48';MMX.fillRect(0,0,w,h);if(state.scene==='world'){for(let ty=Math.floor(pty-range);ty<=Math.ceil(pty+range);ty++)for(let tx=Math.floor(ptx-range);tx<=Math.ceil(ptx+range);tx++){const px=cx+(tx-ptx)*scale,py=cy+(ty-pty)*scale,b=biomeAt(tx*T,ty*T);MMX.fillStyle=waterTile(tx,ty)?'#4d7777':pathTile(tx,ty)?'#9a8966':b==='mountain'?'#74786a':b==='marsh'?'#51644d':b==='goblin'?'#747044':b==='ruins'?'#606557':'#587448';MMX.fillRect(px-1,py-1,scale+1,scale+1)}for(const hse of cityPlots){const px=cx+(hse[0]-ptx)*scale,py=cy+(hse[1]-pty)*scale;if(Math.hypot(px-cx,py-cy)<83){MMX.fillStyle='#6d432e';MMX.fillRect(px-3,py-4,7,7)}}for(const n of npcs){const px=cx+(n.x/T-ptx)*scale,py=cy+(n.y/T-pty)*scale;if(Math.hypot(px-cx,py-cy)<82){MMX.fillStyle='#e6d8a8';MMX.fillRect(px-1.5,py-1.5,3,3)}}for(const e of enemies){if(e.dead)continue;const px=cx+(e.x/T-ptx)*scale,py=cy+(e.y/T-pty)*scale;if(Math.hypot(px-cx,py-cy)<82){MMX.fillStyle='#a94b42';MMX.beginPath();MMX.arc(px,py,2.2,0,7);MMX.fill()}}const g=questTarget(),gx=cx+(g.x/T-ptx)*scale,gy=cy+(g.y/T-pty)*scale;if(Math.hypot(gx-cx,gy-cy)<80){MMX.strokeStyle='#f1cb61';MMX.lineWidth=2;MMX.beginPath();MMX.arc(gx,gy,4+Math.sin(time*4),0,7);MMX.stroke()}}else{MMX.fillStyle='#3e463c';MMX.fillRect(0,0,w,h);MMX.fillStyle='#aa986c';MMX.font='12px Georgia';MMX.textAlign='center';MMX.fillText('notranjost',cx,cy-18)}MMX.translate(cx,cy);MMX.rotate(({up:0,right:Math.PI/2,down:Math.PI,left:-Math.PI/2}[state.dir]||0));MMX.fillStyle='#f5e6ad';MMX.strokeStyle='#2b2417';MMX.lineWidth=2;MMX.beginPath();MMX.moveTo(0,-8);MMX.lineTo(6,7);MMX.lineTo(0,4);MMX.lineTo(-6,7);MMX.closePath();MMX.fill();MMX.stroke();MMX.restore();$('minimapName').textContent=state.scene==='world'?locationAt(ptx,pty,currentRegion):'Notranjost'}
function toggleMap(){mapOpen=!mapOpen;ui.map.classList.toggle('hidden',!mapOpen);A.play('ui');if(mapOpen)drawMap()}
function drawDrop(o){if(o.taken||o.scene!==state.scene||!visible(o.x,o.y,50))return;const x=sx(o.x),y=sy(o.y)+Math.sin(time*3+o.bob)*2;X.fillStyle='#f0d47755';X.beginPath();X.ellipse(x,y+5,14,6,0,0,7);X.fill();X.font='17px sans-serif';X.textAlign='center';X.fillText(items[o.item].icon,x,y);if(o.n>1){X.fillStyle='#fff1ba';X.font='9px Georgia';X.fillText('×'+o.n,x+11,y+7)}}
function drawMazeEntrance(){const p=portals.find(v=>v.id==='shadowMaze'),x=sx(p.x),y=sy(p.y);if(!visible(p.x,p.y,90))return;shadow(p.x,p.y,32);X.fillStyle='#4b5148';X.beginPath();X.ellipse(x,y-4,34,31,0,Math.PI,0);X.lineTo(x+34,y+13);X.lineTo(x-34,y+13);X.fill();X.fillStyle='#171c1b';X.beginPath();X.ellipse(x,y+5,20,24,0,Math.PI,0);X.lineTo(x+20,y+14);X.lineTo(x-20,y+14);X.fill();X.strokeStyle='#9a8650';X.lineWidth=2;X.beginPath();X.arc(x,y+1,27,Math.PI,Math.PI*2);X.stroke();X.fillStyle='#d6b954';X.font='10px Georgia';X.textAlign='center';X.fillText('III',x,y-26)}
const drawBaseProps=props;props=function(){for(const o of exploreSites)exploreProp(o);for(const o of loot)drawDrop(o);drawMazeEntrance();drawBaseProps()};
for(const p of portals){if(p.id==='miraHouse')p.name='Miroslavina hiša';if(p.id==='riverMill')p.name='Jaromirov mlin'}
const speakBase=speak;speak=function(name,lines,end){const who={Mira:'Miroslava',Iva:'Živana','General Grub':'Vojvoda Gromobor','General Nib':'Vojvoda Črnomir','Kovač Bor':'Kovač Borislav','Mlinar Jure':'Mlinar Jaromir'}[name]||name;speakBase(who,lines.map(v=>v.replaceAll('Arin','Kresnik').replaceAll('Grub','Gromobor').replaceAll('Nib','Črnomir')),end)};
const renameLore=s=>s.replaceAll('Mira','Miroslava').replaceAll('Grub','Gromobor').replaceAll('Nib','Črnomir').replaceAll('kovača Bora','kovača Borislava').replaceAll('kovaču Boru','kovaču Borislavu').replaceAll('Mlinar Jure','Mlinar Jaromir').replaceAll('mlinarja Jureta','mlinarja Jaromira').replaceAll('mlinarju Juretu','mlinarju Jaromiru');for(const q of Object.values(quests)){q[1]=renameLore(q[1]);q[2]=q[2].map(renameLore)}
const questTargetBase=questTarget;questTarget=function(){const q=questTargetBase();q.label=q.label.replace('Miro','Miroslavo').replace('generala Gruba','vojvodo Gromobora').replace('generala Niba','vojvodo Črnomira').replace('kovača Bora','kovača Borislava').replace('kovaču Boru','kovaču Borislavu').replace('mlinarja Jureta','mlinarja Jaromira');return q};
function dropLoot(e){const drops=[{item:'bones',n:1},{item:'coin',n:e.type==='boss'?18:2+Math.floor(Math.random()*5)}];if(e.type==='goblin'&&Math.random()<.45)drops.push({item:Math.random()<.18?'ironScimitar':'scrap',n:1});if(e.type==='wolf'&&Math.random()<.55)drops.push({item:'hide',n:1});if(Math.random()<.28)drops.push({item:'bread',n:1});drops.forEach((d,i)=>loot.push({id:e.id+'_'+i,item:d.item,n:d.n,x:e.x+(i-1)*15,y:e.y+8+Math.abs(i-1)*8,scene:state.scene,bob:Math.random()*6.28}))}
function pickupLoot(o){state.inventory[o.item]=(state.inventory[o.item]||0)+o.n;o.taken=true;A.play('pickup');floatText('+'+o.n+' '+items[o.item].name,o.x,o.y-18);updateUI();save()}
kill=function(e){e.dead=true;gain('combat',e.type==='boss'?55:e.type==='goblin'?12:e.type==='wolf'?10:7);dropLoot(e);if(e.id==='boglug'){state.bossDead=true;setQuest(7,'Boglug je premagan. Vrni se k Miri.')}if(e.id==='gromovnik'){state.stormDead=true;setQuest(19,'Gromovnik je premagan. Vrni se k Radovanu.')}if(e.id==='povodni'){state.waterDead=true;state.inventory.waterPearl=1;setQuest(24,'Prejel si biser. Vrni se k mlinarju Juretu.')}A.play('quest');emit(e.x,e.y,'#edc568',e.type==='boss'?45:12)};
const buildBaseWorld=buildWorld;buildWorld=function(){buildBaseWorld();const maze=portals.find(p=>p.id==='shadowMaze');for(let i=resources.length-1;i>=0;i--)if(exploreSites.some(o=>Math.hypot(o.x-resources[i].x,o.y-resources[i].y)<48)||Math.hypot(maze.x-resources[i].x,maze.y-resources[i].y)<70)resources.splice(i,1)};
const nearestBase=nearest;nearest=function(){nearestBase();for(const o of loot){if(o.taken||o.scene!==state.scene)continue;const q=Math.hypot(o.x-state.x,o.y-state.y);if(q<44){target={kind:'loot',o,label:'Poberi: '+items[o.item].name};ui.prompt.classList.add('show');ui.prompt.innerHTML='<b>E</b> · '+target.label;break}}};
const interactBase=interact;interact=function(){if(target?.kind==='loot'){A.init();pickupLoot(target.o);target=null;return}interactBase()};
const solidBase=solidAt;solidAt=function(x,y,r=10){if(state.scene!=='shadowMaze')return solidBase(x,y,r);if(x<56||x>W-56||y<82||y>H-55)return true;for(const q of[[320,82,24,278],[320,430,24,115],[480,230,24,315],[650,82,24,278],[650,430,24,115]])if(x+r>q[0]&&x-r<q[0]+q[2]&&y+r>q[1]&&y-r<q[1]+q[3])return true;return false};
const interiorBase=drawInteriorDetails;drawInteriorDetails=function(){interiorBase();if(state.scene!=='shadowMaze')return;X.fillStyle='#141817';X.fillRect(0,72,W,H-122);X.fillStyle='#3f4742';for(let y=82;y<H-50;y+=32)for(let x=56;x<W-56;x+=32){X.fillStyle=(x+y)%64?'#3b433e':'#444b44';X.fillRect(x,y,30,30)}X.fillStyle='#171b19';for(const q of[[320,82,24,278],[320,430,24,115],[480,230,24,315],[650,82,24,278],[650,430,24,115]]){X.fillRect(q[0],q[1],q[2],q[3]);X.strokeStyle='#697067';X.strokeRect(q[0],q[1],q[2],q[3])}X.fillStyle='#9b7936';X.fillRect(W/2+115,H/2-15,40,30);X.fillStyle='#efcb55';X.fillRect(W/2+130,H/2-15,6,30)};
const chestBase=openChest;openChest=function(){if(state.scene!=='shadowMaze'){chestBase();return}if(state.chests.shadowMaze){notify('Zlata skrinja je prazna.');return}state.chests.shadowMaze=true;state.inventory.goldScimitar=1;state.inventory.sunShield=1;gain('combat',80);gain('defence',80);A.play('quest');speak('Skrinja kralja Samota',['V zlati skrinji počivata ukrivljeno rezilo in ščit s tremi sonci.','DOBIL SI: Zlati krivec kralja Samota, Ščit treh sonc, 80 bojnih EXP in 80 obrambnih EXP.'],()=>{updateUI();save()})};
function useInventoryItem(k){if(!state.inventory[k])return;if(k==='bones'){state.inventory[k]--;gain('spirit',12);A.play('quest');notify('Kosti si položil v zemljo. +12 izročila.')}else if(k==='bread'){if(state.hp>=state.maxHp)return;state.inventory[k]--;state.hp=Math.min(state.maxHp,state.hp+22);A.play('heal');notify('Kruh ti povrne 22 življenja.')}else useMushroom();updateUI();save()}
selectItem=function(k,quiet=false){selectedItem=k;const d=items[k],n=state.inventory[k]||0,canEquip=d.weapon&&state.level>=d.level,equipped=state.weapon===k||state.armor===k||state.shield===k;ui.detail.innerHTML=`${d.use&&n?'<button id="useItem">Uporabi</button>':''}${d.weapon?`<button id="equipItem">${state.weapon===k?'Opremljeno':canEquip?'Opremi':'Raven '+d.level}</button>`:''}${d.armor?`<button id="equipItem">${equipped?'Opremljeno':'Opremi'}</button>`:''}<span>${d.name} · ${n}</span><small>${d.desc}</small>`;if(d.use&&n)$('useItem').onclick=()=>useInventoryItem(k);if(d.weapon||d.armor)$('equipItem').onclick=()=>{if(d.weapon&&!canEquip){notify('Potrebuješ '+d.level+'. bojno raven.');return}if(d.weapon)state.weapon=k;else if(k==='sunShield')state.shield=k;else state.armor=k;A.play('ui');notify('Opremljeno: '+d.name);updateUI();save()};if(!quiet)updateUI()};
hurt=function(n){if(player.invuln||state.hp<=0)return;const guard=(items[state.armor]?.armor||0)+(items[state.shield]?.armor||0),damage=Math.max(1,n-guard);state.hp-=damage;gain('defence',2);player.invuln=.85;shake=8;A.play('hurt');floatText('-'+damage,state.x,state.y-28,'#ff8478');if(state.hp<=0){state.hp=0;ui.death.classList.remove('hidden')}updateUI()};
const drawBaseMinimap=drawMinimap;drawMinimap=function(){drawBaseMinimap();if(state.scene!=='world')return;const cx=MMC.width/2,cy=MMC.height/2,ptx=state.x/T,pty=state.y/T;MMX.save();for(const o of exploreSites){const x=cx+(o.x/T-ptx)*7,y=cy+(o.y/T-pty)*7;if(Math.hypot(x-cx,y-cy)>78)continue;MMX.fillStyle=state.discoveries[o.id]?'#8d8060':'#f0cf67';MMX.beginPath();MMX.moveTo(x,y-3);MMX.lineTo(x+3,y);MMX.lineTo(x,y+3);MMX.lineTo(x-3,y);MMX.closePath();MMX.fill()}MMX.restore()};
$('minimapOpen').onclick=toggleMap;
function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;update(dt);drawWorld();drawMinimap();if(mapOpen)drawMap();requestAnimationFrame(loop)}
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','e',' ','1','m','escape'].includes(k))e.preventDefault();A.init();if(!e.repeat){if(k==='e')interact();if(k===' ')attack();if(k==='1')useMushroom();if(k==='m'&&!menuOpen)toggleMap();if(k==='escape')toggleMenu()}keys[k]=true});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
function toggleMenu(force){menuOpen=force===undefined?!menuOpen:force;$('mainMenu').classList.toggle('hidden',!menuOpen);if(menuOpen){renderSlots();save()}A.play('ui')}
function startNew(){if(localStorage.getItem('mah-save-current')&&!confirm('Začnem novo zgodbo? Trenutno igro lahko prej shraniš v režo.'))return;localStorage.removeItem('mah-save-current');hydrate(null);resources.length=enemies.length=fireflies.length=clouds.length=0;buildWorld();updateUI();toggleMenu(false);transitionTip()}
function showMenuPanel(kind){const p=$('menuPanel');$('saveSlots').classList.add('hidden');p.classList.remove('hidden');if(kind==='settings'){p.innerHTML=`<h3>Nastavitve in kontrole</h3><label>Polni vremenski učinki <input id="weatherSetting" type="checkbox" ${state.settings.weatherFx?'checked':''}></label><label>Tresenje zaslona <input id="shakeSetting" type="checkbox" ${state.settings.screenShake?'checked':''}></label><p><kbd>WASD</kbd> ali puščice — premik<br><kbd>E</kbd> — pogovor, vrata in nabiranje<br><kbd>Space</kbd> — hiter zaporedni napad<br><kbd>M</kbd> — zemljevid · <kbd>1</kbd> — zaužij gobo · <kbd>Esc</kbd> — meni</p><button id="panelClose">Zapri</button>`;$('weatherSetting').onchange=e=>{state.settings.weatherFx=e.target.checked;save()};$('shakeSetting').onchange=e=>{state.settings.screenShake=e.target.checked;save()}}else p.innerHTML='<h3>Zasluge</h3><p>Zasnova, svet in izvedba: Mah in žerjavica.<br>Izvirni svet temelji na slovenskem pripovednem izročilu. Vizualni elementi so bili ustvarjeni posebej za projekt. Glasbene datoteke in licence so navedene v assets/audio/CREDITS.md.</p><p>Navdih: počasno raziskovanje starih računalniških RPG-jev, slovenska krajina in ljudske pripovedke. Nobena mapa, melodija ali lik ni kopija druge igre.</p><button id="panelClose">Zapri</button>';$('panelClose').onclick=()=>p.classList.add('hidden');A.play('ui')}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button,.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active');A.play('ui')});document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.onpointerdown=e=>{e.preventDefault();A.init();keys[k]=true};b.onpointerup=b.onpointercancel=b.onpointerleave=()=>keys[k]=false});document.querySelector('[data-tap="interact"]').onclick=interact;document.querySelector('[data-tap="attack"]').onclick=attack;$('mapBtn').onclick=$('closeMap').onclick=toggleMap;$('soundBtn').onclick=()=>{$('soundBtn').textContent=A.toggle()?'♫':'♩'};$('menuBtn').onclick=()=>toggleMenu();$('continueBtn').onclick=()=>toggleMenu(false);$('loadBtn').onclick=()=>{$('saveSlots').classList.toggle('hidden');renderSlots()};$('menuNewBtn').onclick=startNew;$('rewardBtn').onclick=()=>ui.questReward.classList.add('hidden');$('wakeBtn').onclick=()=>{state.hp=state.maxHp;state.scene='world';state.x=camp.x;state.y=camp.y;ui.death.classList.add('hidden');updateUI();save()};addEventListener('beforeunload',save);
$('settingsBtn').onclick=()=>showMenuPanel('settings');$('creditsBtn').onclick=()=>showMenuPanel('credits');
load();buildWorld();updateUI();renderSlots();ui.track.textContent=A.trackName();setTimeout(()=>$('loadingScreen').classList.add('fade'),2200);setTimeout(()=>{$('loadingScreen').classList.add('hidden');$('mainMenu').classList.remove('hidden')},3000);setTimeout(()=>{const t=$('titleCard');if(t)t.remove()},6200);requestAnimationFrame(loop);
})();
