(function(){
  'use strict';
  const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
  const W=canvas.width,H=canvas.height,T=32,WORLD_W=64,WORLD_H=42,A=window.GameAudio;
  const $=id=>document.getElementById(id),ui={toast:$('toast'),prompt:$('prompt'),dialogue:$('dialogue'),speaker:$('speaker'),text:$('dialogueText'),portrait:$('portrait'),hp:$('hpBar'),hpText:$('hpText'),xp:$('xpBar'),xpText:$('xpText'),level:$('level'),inventory:$('inventory'),skills:$('skillList'),questTitle:$('questTitle'),questText:$('questText'),objectives:$('objectives'),location:$('location'),death:$('death')};
  const keys={},particles=[],floaters=[],fireflies=[],resources=[],enemies=[];let last=performance.now(),camera={x:0,y:0},shake=0,toastTimer,dialogue=null,actionTarget=null,saveClock=0,gameTime=0;
  const itemData={wood:{icon:'🪵',name:'Jelšev les'},mushroom:{icon:'🍄',name:'Žerjavna goba',usable:true},ore:{icon:'◆',name:'Modra ruda'},coin:{icon:'●',name:'Bakrenec'},charm:{icon:'✦',name:'Žerjavni talisman'}};
  const skillNames={woodcut:'Drvarjenje',forage:'Nabiralništvo',combat:'Bojevanje',mining:'Rudarjenje'};
  const seeded=(x,y,n=0)=>{const v=Math.sin(x*127.1+y*311.7+n*71.9)*43758.5453;return v-Math.floor(v)};
  const waterAt=(x,y)=>{const tx=Math.floor(x/T),ty=Math.floor(y/T);return tx<1||ty<1||tx>=WORLD_W-1||ty>=WORLD_H-1||(tx>25&&tx<31&&ty>0&&ty<18)||(tx>27&&tx<34&&ty>14&&ty<27&&!(ty>19&&ty<23));};
  const pathAt=(tx,ty)=>(ty>=25&&ty<=27&&tx>3&&tx<45)||(tx>=42&&tx<=44&&ty>8&&ty<27);
  const NPCS=[{id:'brin',x:9*T,y:25*T,name:'Brin',color:'#9d7541',hair:'#d1b36a'},{id:'iva',x:17*T,y:22*T,name:'Iva',color:'#76588f',hair:'#39291f'}];
  const shrine={x:51*T,y:9*T};
  function baseState(){return{x:11*T,y:27*T,hp:100,maxHp:100,xp:0,level:1,inventory:{wood:0,mushroom:1,ore:0,coin:0,charm:0},skills:{woodcut:0,forage:0,combat:0,mining:0},quest:0,harvested:{},bossDefeated:false,dir:0,playtime:0}}
  let state=baseState(),player={vx:0,vy:0,attack:0,invuln:0,walk:0};
  function load(){try{const saved=JSON.parse(localStorage.getItem('mahInZerjavica'));if(saved&&saved.inventory){state=Object.assign(baseState(),saved);state.inventory=Object.assign(baseState().inventory,saved.inventory);state.skills=Object.assign(baseState().skills,saved.skills)}}catch(e){state=baseState()}}
  function save(){state.playtime=(state.playtime||0)+saveClock;saveClock=0;localStorage.setItem('mahInZerjavica',JSON.stringify(state))}
  function addResource(type,tx,ty,id){resources.push({type,x:tx*T,y:ty*T,id,hp:type==='tree'?3:type==='rock'?4:1,maxHp:type==='tree'?3:type==='rock'?4:1,bump:0})}
  function buildWorld(){
    for(let y=2;y<WORLD_H-2;y++)for(let x=2;x<WORLD_W-2;x++){
      if(waterAt(x*T,y*T)||pathAt(x,y)||(x>5&&x<20&&y>20&&y<31)||(x>47&&x<56&&y>6&&y<13))continue;
      const r=seeded(x,y);if(r>.88)addResource('tree',x,y,'t'+x+'_'+y);else if(r<.035)addResource('rock',x,y,'r'+x+'_'+y);else if(r>.805&&r<.825)addResource('mushroom',x,y,'m'+x+'_'+y);
    }
    [[13,18],[19,30],[35,12],[39,31],[48,20]].forEach((p,i)=>addResource('mushroom',p[0],p[1],'specialm'+i));
    const mobs=[[22,29],[34,30],[38,19],[46,24],[56,17],[16,15],[42,6]];mobs.forEach((p,i)=>enemies.push(makeEnemy(i<4?'slime':'wisp',p[0]*T,p[1]*T,i)));
    for(let i=0;i<35;i++)fireflies.push({x:seeded(i,2)*WORLD_W*T,y:seeded(i,9)*WORLD_H*T,p:seeded(i,5)*6.28,s:8+seeded(i,8)*10});
  }
  function makeEnemy(type,x,y,id){const boss=type==='warden';return{type,x,y,id,hp:boss?14:type==='wisp'?5:4,maxHp:boss?14:type==='wisp'?5:4,speed:boss?55:type==='wisp'?45:32,hit:0,attack:0,phase:seeded(id||1,7)*6.2,dead:false}}
  function solidAt(x,y,r=10){if(waterAt(x,y))return true;for(const n of NPCS)if(Math.hypot(x-n.x,y-n.y)<r+14)return true;for(const o of resources)if(!state.harvested[o.id]&&o.type!=='mushroom'&&Math.hypot(x-o.x,y-o.y)<r+13)return true;return false}
  function notify(text){clearTimeout(toastTimer);ui.toast.textContent=text;ui.toast.classList.add('show');toastTimer=setTimeout(()=>ui.toast.classList.remove('show'),1900)}
  function emit(x,y,color,count=8){for(let i=0;i<count;i++)particles.push({x,y,vx:(Math.random()-.5)*90,vy:-20-Math.random()*80,life:.5+Math.random()*.45,color,size:2+Math.random()*3})}
  function floater(text,x,y,color='#f3db8d'){floaters.push({text,x,y,life:1,color})}
  function gainSkill(skill,n){state.skills[skill]+=n;const old=state.level;state.xp+=n;state.level=1+Math.floor(Math.sqrt(state.xp/40));if(state.level>old){state.maxHp+=10;state.hp=state.maxHp;A.play('level');notify('Nova raven! Moč v tebi raste.')}updateUI()}
  function addItem(item,n=1){state.inventory[item]=(state.inventory[item]||0)+n;A.play('pickup');floater('+'+n+' '+itemData[item].name,state.x,state.y-20);updateUI();save()}
  function useMushroom(){if(state.inventory.mushroom<1||state.hp>=state.maxHp)return;state.inventory.mushroom--;state.hp=Math.min(state.maxHp,state.hp+35);A.play('heal');emit(state.x,state.y,'#9bd36c',12);notify('Toplota gobe zaceli rane.');updateUI();save()}
  function startDialogue(speaker,lines,onEnd){dialogue={speaker,lines,index:0,onEnd};state.vx=state.vy=0;showLine()}
  function showLine(){const line=dialogue.lines[dialogue.index];ui.speaker.textContent=dialogue.speaker;ui.portrait.textContent=dialogue.speaker[0];ui.text.textContent=line;ui.dialogue.classList.remove('hidden');A.play('talk')}
  function advanceDialogue(){if(!dialogue)return;dialogue.index++;if(dialogue.index>=dialogue.lines.length){ui.dialogue.classList.add('hidden');const cb=dialogue.onEnd;dialogue=null;if(cb)cb()}else showLine()}
  function talkBrin(){
    if(state.quest===0)startDialogue('Brin',['Tudi ti slišiš šepet, kajne? Stari hrast se prebuja, vendar je njegova iskra hladna.','Prinesi mi štiri polena jelše in tri žerjavne gobe. Iz njih bom spletel talisman.'],()=>{state.quest=1;A.play('quest');notify('Nova naloga: Glas v megli');updateUI();save()});
    else if(state.quest===1&&state.inventory.wood>=4&&state.inventory.mushroom>=3)startDialogue('Brin',['Les pomni sonce. Goba pomni ogenj. Zdaj bosta pomnila tudi tebe.','Odnesi talisman kamnitemu krogu ob starem hrastu na severovzhodu. In bodi previden.'],()=>{state.inventory.wood-=4;state.inventory.mushroom-=3;state.inventory.charm=1;state.quest=2;A.play('quest');updateUI();save()});
    else if(state.quest===1)startDialogue('Brin',[`Še vedno potrebujem ${Math.max(0,4-state.inventory.wood)} polen in ${Math.max(0,3-state.inventory.mushroom)} gob.`]);
    else if(state.quest===2||state.quest===3)startDialogue('Brin',['Kamniti krog leži onkraj reke, kjer drevesa rastejo kot prsti proti nebu.']);
    else if(state.quest===4)startDialogue('Brin',['Megla je izgubila svoj glas. Ti pa si našel svojega. Dolina Jelše te odslej pozna po imenu.'],()=>{state.quest=5;state.inventory.coin+=30;A.play('quest');notify('Naloga opravljena · +30 bakrencev');updateUI();save()});
    else startDialogue('Brin',['Poslušaj listje. Danes pripoveduje o tebi.']);
  }
  function talkIva(){startDialogue('Iva',state.quest<2?['Brin se dela pogumnega, a ponoči ne zapusti ognja.','Žerjavne gobe rastejo v senci. Njihove rdeče kapice žarijo tudi v megli.']:['Reka ima plitev prehod južno od tod. Kamni pod vodo so skoraj kot most.'])}
  function activateShrine(){if(state.quest!==2){notify(state.quest<2?'Kamen je mrzel in tih.':'V krogu ostaja le topel pepel.');return}state.inventory.charm=0;state.quest=3;const boss=makeEnemy('warden',52*T,8*T,'boss');enemies.push(boss);shake=12;emit(shrine.x,shrine.y,'#e6ad4d',30);A.play('quest');startDialogue('Glas hrasta',['Tujec nosi mojo ukradeno iskro. Dokaži, da nisi le še ena lakomna senca.']);updateUI();save()}
  function interact(){if(dialogue){advanceDialogue();return}if(!actionTarget)return;const a=actionTarget;if(a.kind==='npc'){a.obj.id==='brin'?talkBrin():talkIva();return}if(a.kind==='shrine'){activateShrine();return}const o=a.obj;o.bump=1;if(o.type==='tree'||o.type==='rock'){A.play(o.type==='tree'?'chop':'mine');o.hp--;emit(o.x,o.y,o.type==='tree'?'#a77a43':'#91a3a5',7);if(o.hp<=0){state.harvested[o.id]=true;addItem(o.type==='tree'?'wood':'ore');gainSkill(o.type==='tree'?'woodcut':'mining',o.type==='tree'?6:8)}}else{state.harvested[o.id]=true;addItem('mushroom');gainSkill('forage',5)}updateUI()}
  function attack(){if(dialogue||player.attack>0)return;player.attack=.32;A.play('hit');let hit=false;for(const e of enemies){if(e.dead)continue;const d=Math.hypot(e.x-state.x,e.y-state.y);if(d<48){const dmg=1+Math.floor(state.level/3);e.hp-=dmg;e.hit=.25;hit=true;floater('-'+dmg,e.x,e.y-20,'#ffd38a');emit(e.x,e.y,e.type==='wisp'?'#8fd6b8':'#83b95c',8);if(e.hp<=0)killEnemy(e)}}if(hit)shake=3}
  function killEnemy(e){e.dead=true;gainSkill('combat',e.type==='warden'?35:e.type==='wisp'?10:7);addItem('coin',e.type==='warden'?20:1+Math.floor(Math.random()*3));if(e.type==='warden'){state.bossDefeated=true;state.quest=4;A.play('quest');notify('Varuh megle je premagan. Vrni se k Brinu.');emit(e.x,e.y,'#edc568',40);updateUI();save()}}
  function hurt(n){if(player.invuln>0)return;state.hp-=n;player.invuln=.8;shake=7;A.play('hurt');floater('-'+n,state.x,state.y-25,'#ff8175');updateUI();if(state.hp<=0){state.hp=0;ui.death.classList.remove('hidden');save()}}
  function updatePlayer(dt){
    let dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);const len=Math.hypot(dx,dy)||1;dx/=len;dy/=len;if(dx||dy)state.dir=Math.atan2(dy,dx);
    const speed=dialogue?0:155,nx=state.x+dx*speed*dt,ny=state.y+dy*speed*dt;if(!solidAt(nx,state.y))state.x=nx;if(!solidAt(state.x,ny))state.y=ny;if(dx||dy){player.walk+=dt*9;if(Math.floor(player.walk)%5===0&&Math.floor((player.walk-dt*9))%5!==0)A.play('step')}
    state.x=Math.max(T,Math.min((WORLD_W-1)*T,state.x));state.y=Math.max(T,Math.min((WORLD_H-1)*T,state.y));player.attack=Math.max(0,player.attack-dt);player.invuln=Math.max(0,player.invuln-dt);
  }
  function updateEnemies(dt){for(const e of enemies){if(e.dead)continue;e.hit=Math.max(0,e.hit-dt);e.attack=Math.max(0,e.attack-dt);const d=Math.hypot(state.x-e.x,state.y-e.y);if(d<230&&!dialogue){const ang=Math.atan2(state.y-e.y,state.x-e.x);const drift=Math.sin(gameTime*1.7+e.phase)*.35;e.x+=Math.cos(ang+drift)*e.speed*dt;e.y+=Math.sin(ang+drift)*e.speed*dt;if(d<29&&e.attack<=0){e.attack=1.15;hurt(e.type==='warden'?16:e.type==='wisp'?10:7)}}}}
  function nearestAction(){let best=null,dist=52;for(const n of NPCS){const d=Math.hypot(n.x-state.x,n.y-state.y);if(d<dist){dist=d;best={kind:'npc',obj:n,label:'Govori z '+n.name}}}for(const o of resources){if(state.harvested[o.id])continue;const d=Math.hypot(o.x-state.x,o.y-state.y);if(d<dist){dist=d;best={kind:'resource',obj:o,label:o.type==='tree'?'Posekaj jelšo':o.type==='rock'?'Izkoplji rudo':'Naberi gobo'}}}const ds=Math.hypot(shrine.x-state.x,shrine.y-state.y);if(ds<dist)best={kind:'shrine',label:'Dotakni se kamna'};actionTarget=best;ui.prompt.classList.toggle('show',!!best&&!dialogue);ui.prompt.innerHTML=best?'<b>E</b> · '+best.label:''}
  function updateParticles(dt){for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=110*dt;p.life-=dt}for(const f of floaters){f.y-=26*dt;f.life-=dt}for(let i=particles.length-1;i>=0;i--)if(particles[i].life<=0)particles.splice(i,1);for(let i=floaters.length-1;i>=0;i--)if(floaters[i].life<=0)floaters.splice(i,1);for(const o of resources)o.bump=Math.max(0,o.bump-dt*5)}
  function update(dt){if(state.hp>0){updatePlayer(dt);updateEnemies(dt);nearestAction()}updateParticles(dt);gameTime+=dt;saveClock+=dt;if(saveClock>8)save();camera.x+=(state.x-W/2-camera.x)*Math.min(1,dt*5);camera.y+=(state.y-H/2-camera.y)*Math.min(1,dt*5);camera.x=Math.max(0,Math.min(WORLD_W*T-W,camera.x));camera.y=Math.max(0,Math.min(WORLD_H*T-H,camera.y));shake=Math.max(0,shake-dt*25);ui.location.textContent=locationName()}
  function locationName(){if(state.x>44*T&&state.y<15*T)return'Krog starega hrasta';if(state.x>26*T&&state.x<34*T)return'Reka Šepetalka';if(state.x<23*T&&state.y>19*T)return'Jelševa jasa';return'Megleni gozd'}
  function sx(x){return Math.round(x-camera.x)}function sy(y){return Math.round(y-camera.y)}
  function tile(tx,ty){const x=tx*T-camera.x,y=ty*T-camera.y;if(waterAt(tx*T,ty*T)){ctx.fillStyle='#294c50';ctx.fillRect(x,y,T+1,T+1);ctx.fillStyle='rgba(133,180,168,.25)';const wave=(gameTime*14+tx*9+ty*4)%25;ctx.fillRect(x+wave-8,y+9,9,2);ctx.fillRect(x+24-wave/2,y+23,7,1);return}if(pathAt(tx,ty)){ctx.fillStyle=(tx+ty)%2?'#777052':'#716a4e'}else{const n=seeded(tx,ty);ctx.fillStyle=n>.66?'#3f633c':n>.33?'#456a40':'#496f42'}ctx.fillRect(x,y,T+1,T+1);if(!pathAt(tx,ty)&&seeded(tx,ty,2)>.78){ctx.fillStyle='#6f8b55';ctx.fillRect(x+5+seeded(tx,ty,3)*20,y+6+seeded(tx,ty,4)*18,2,4)}}
  function shadow(x,y,w=24){ctx.fillStyle='rgba(5,9,5,.28)';ctx.beginPath();ctx.ellipse(sx(x),sy(y)+12,w,8,0,0,Math.PI*2);ctx.fill()}
  function drawTree(o){const x=sx(o.x),y=sy(o.y),s=Math.sin(gameTime*1.1+o.x*.01)*1.5+o.bump*4;shadow(o.x,o.y,21);ctx.fillStyle='#604329';ctx.fillRect(x-4,y-3,8,25);ctx.fillStyle='#24452b';ctx.beginPath();ctx.arc(x+s-8,y-13,15,0,7);ctx.arc(x+s+8,y-16,17,0,7);ctx.arc(x+s,y-27,16,0,7);ctx.fill();ctx.fillStyle='#416b39';ctx.fillRect(x+s-7,y-30,8,5);ctx.fillRect(x+s+9,y-19,6,4)}
  function drawRock(o){const x=sx(o.x),y=sy(o.y);shadow(o.x,o.y,16);ctx.fillStyle='#657070';ctx.beginPath();ctx.moveTo(x-17,y+12);ctx.lineTo(x-13,y-8);ctx.lineTo(x+2,y-17);ctx.lineTo(x+17,y-3);ctx.lineTo(x+13,y+13);ctx.fill();ctx.fillStyle='#a2aeaa';ctx.fillRect(x-7,y-8,10,3);ctx.fillStyle='#6599a1';ctx.fillRect(x+4,y-4,4,8)}
  function drawMushroom(o){const x=sx(o.x),y=sy(o.y);ctx.fillStyle='#dfd1a5';ctx.fillRect(x-2,y,4,9);ctx.fillStyle='#c45b45';ctx.beginPath();ctx.arc(x,y,7+Math.sin(gameTime*2+o.x)*.5,Math.PI,Math.PI*2);ctx.fill();ctx.fillStyle='#f2bd76';ctx.fillRect(x-3,y-5,2,2)}
  function drawPerson(x,y,body,hair,walk=0,dir=0){x=sx(x);y=sy(y);shadow(x+camera.x,y+camera.y,12);const bob=Math.abs(Math.sin(walk))*(-2);ctx.fillStyle='#25201a';ctx.fillRect(x-8,y+10+(Math.sin(walk)>0?2:0),6,11);ctx.fillRect(x+2,y+10+(Math.sin(walk)<0?2:0),6,11);ctx.fillStyle=body;ctx.fillRect(x-10,y-7+bob,20,20);ctx.fillStyle='#c99769';ctx.fillRect(x-7,y-17+bob,14,12);ctx.fillStyle=hair;ctx.fillRect(x-8,y-20+bob,16,6);ctx.fillStyle='#201d18';const side=Math.cos(dir)>0?2:-2;ctx.fillRect(x+side-1,y-13+bob,2,2)}
  function drawEnemy(e){const x=sx(e.x),y=sy(e.y),pulse=Math.sin(gameTime*4+e.phase);shadow(e.x,e.y,e.type==='warden'?25:14);ctx.save();if(e.hit)ctx.globalAlpha=.55;if(e.type==='slime'){ctx.fillStyle='#70a64c';ctx.beginPath();ctx.ellipse(x,y+2,16+pulse,13-pulse*.5,0,Math.PI,0);ctx.lineTo(x+16,y+11);ctx.lineTo(x-16,y+11);ctx.fill();ctx.fillStyle='#182014';ctx.fillRect(x-7,y,3,3);ctx.fillRect(x+5,y,3,3)}else{const boss=e.type==='warden',r=boss?24:12;ctx.globalAlpha=e.hit?.55:.78;ctx.fillStyle=boss?'#c8a653':'#67b99f';ctx.beginPath();ctx.arc(x,y,r+pulse*2,0,7);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle='#f3edb6';ctx.fillRect(x-5,y-3,3,3);ctx.fillRect(x+3,y-3,3,3);for(let i=0;i<(boss?7:3);i++){ctx.fillStyle=boss?'#e4b94f':'#95d8bd';ctx.fillRect(x+Math.cos(gameTime*1.4+i)*r*1.5,y+Math.sin(gameTime*1.7+i)*r*1.2,3,3)}}ctx.restore();if(e.hp<e.maxHp){ctx.fillStyle='#171b17';ctx.fillRect(x-18,y-(e.type==='warden'?34:23),36,4);ctx.fillStyle='#c45b4f';ctx.fillRect(x-18,y-(e.type==='warden'?34:23),36*e.hp/e.maxHp,4)}}
  function drawShrine(){const x=sx(shrine.x),y=sy(shrine.y);for(let i=0;i<7;i++){const a=i/7*Math.PI*2,rx=x+Math.cos(a)*38,ry=y+Math.sin(a)*20;ctx.fillStyle='#6c746c';ctx.fillRect(rx-5,ry-11,10,22);ctx.fillStyle=state.quest===2?'#c59749':'#496859';ctx.fillRect(rx-2,ry-7,4,6)}ctx.fillStyle='rgba(221,173,75,'+(.12+Math.sin(gameTime*2)*.05)+')';ctx.beginPath();ctx.arc(x,y,28,0,7);ctx.fill()}
  function drawHouse(){const x=sx(13*T),y=sy(23*T);ctx.fillStyle='#6e5737';ctx.fillRect(x-53,y-55,106,68);ctx.fillStyle='#3b3024';ctx.beginPath();ctx.moveTo(x-63,y-53);ctx.lineTo(x,y-92);ctx.lineTo(x+63,y-53);ctx.fill();ctx.fillStyle='#d5a357';ctx.fillRect(x-8,y-17,16,30);ctx.fillStyle='#94b48d';ctx.fillRect(x-38,y-36,17,15);ctx.fillStyle='#2c3027';ctx.fillRect(x-34,y-32,4,11);ctx.fillRect(x-27,y-32,3,11)}
  function drawCampfire(){const x=sx(8*T),y=sy(28*T),f=Math.sin(gameTime*9)*3;ctx.fillStyle='#5c3b25';ctx.fillRect(x-12,y+7,24,5);ctx.fillStyle='#e66f3d';ctx.beginPath();ctx.moveTo(x,y+8);ctx.quadraticCurveTo(x-11,y-1,x-3,y-17-f);ctx.quadraticCurveTo(x+13,y-2,x,y+8);ctx.fill();ctx.fillStyle='#ffd268';ctx.beginPath();ctx.moveTo(x,y+5);ctx.quadraticCurveTo(x-5,y,x+1,y-10+f);ctx.quadraticCurveTo(x+6,y+1,x,y+5);ctx.fill()}
  function draw(){ctx.clearRect(0,0,W,H);const jx=shake?(Math.random()-.5)*shake:0,jy=shake?(Math.random()-.5)*shake:0;ctx.save();ctx.translate(jx,jy);const minX=Math.floor(camera.x/T),maxX=Math.ceil((camera.x+W)/T),minY=Math.floor(camera.y/T),maxY=Math.ceil((camera.y+H)/T);for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++)tile(x,y);drawHouse();drawCampfire();drawShrine();
    const draws=[];for(const o of resources)if(!state.harvested[o.id])draws.push({y:o.y,fn:()=>o.type==='tree'?drawTree(o):o.type==='rock'?drawRock(o):drawMushroom(o)});for(const n of NPCS)draws.push({y:n.y,fn:()=>{drawPerson(n.x,n.y,n.color,n.hair,0,0);ctx.fillStyle='#e8d9a9';ctx.font='11px Georgia';ctx.textAlign='center';ctx.fillText(n.name,sx(n.x),sy(n.y)-27)}});for(const e of enemies)if(!e.dead)draws.push({y:e.y,fn:()=>drawEnemy(e)});draws.push({y:state.y,fn:()=>{if(player.invuln&&Math.floor(player.invuln*12)%2)return;drawPerson(state.x,state.y,'#496b8f','#4b3428',player.walk,state.dir);if(player.attack){ctx.strokeStyle='#ecd184';ctx.lineWidth=3;ctx.beginPath();ctx.arc(sx(state.x),sy(state.y),30,state.dir-.8,state.dir+.8);ctx.stroke()}}});draws.sort((a,b)=>a.y-b.y).forEach(d=>d.fn());
    for(const f of fireflies){const a=.25+.55*(Math.sin(gameTime*2+f.p)*.5+.5),x=sx(f.x+Math.sin(gameTime+f.p)*f.s),y=sy(f.y+Math.cos(gameTime*.8+f.p)*f.s);if(x>0&&x<W&&y>0&&y<H){ctx.fillStyle=`rgba(239,211,105,${a})`;ctx.fillRect(x,y,2,2)}}for(const p of particles){ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.fillRect(sx(p.x),sy(p.y),p.size,p.size)}ctx.globalAlpha=1;for(const f of floaters){ctx.globalAlpha=Math.max(0,f.life);ctx.fillStyle=f.color;ctx.font='bold 12px Georgia';ctx.textAlign='center';ctx.fillText(f.text,sx(f.x),sy(f.y))}ctx.globalAlpha=1;ctx.restore()}
  const quests={0:{title:'Glas v megli',text:'Brin čaka pri svoji hiši na Jelševi jasi.',obj:['Pogovori se z Brinom']},1:{title:'Spomin lesa',text:'Brin potrebuje sestavine za žerjavni talisman.',obj:['Zberi 4 polena jelše','Zberi 3 žerjavne gobe','Vrni se k Brinu']},2:{title:'Stari krog',text:'Odnesi talisman v kamniti krog na severovzhodu.',obj:['Poišči kamniti krog','Položi talisman med kamne']},3:{title:'Varuh megle',text:'Prebujeni varuh ti zapira pot. Premagaj ga.',obj:['Premagaj varuha starega hrasta']},4:{title:'Jutro v Jelšah',text:'Megla se umika. Brin mora izvedeti, kaj se je zgodilo.',obj:['Vrni se k Brinu']},5:{title:'Dolina te pozna',text:'Stari hrast spet sanja. Za zdaj je dolina varna.',obj:['Naloga opravljena']}};
  function updateUI(){ui.hp.style.width=100*state.hp/state.maxHp+'%';ui.hpText.value=Math.ceil(state.hp)+' / '+state.maxHp;const prev=40*(state.level-1)*(state.level-1),next=40*state.level*state.level;ui.xp.style.width=100*(state.xp-prev)/(next-prev)+'%';ui.xpText.value=state.xp+' / '+next;ui.level.textContent=state.level;ui.inventory.innerHTML=Object.keys(itemData).concat(['empty','empty2','empty3']).map(k=>{if(k.startsWith('empty'))return'<div class="slot"></div>';const d=itemData[k],n=state.inventory[k]||0;return`<button class="slot ${d.usable&&n?'usable':''}" data-item="${k}" aria-label="${d.name}: ${n}">${d.icon}<small>${n}</small><em>${d.name}</em></button>`}).join('');ui.inventory.querySelectorAll('[data-item="mushroom"]').forEach(b=>b.onclick=useMushroom);ui.skills.innerHTML=Object.entries(state.skills).map(([k,v])=>{const lvl=1+Math.floor(Math.sqrt(v/25)),prev=25*(lvl-1)*(lvl-1),next=25*lvl*lvl;return`<div class="skill-row"><div><span>${skillNames[k]}</span><b>${lvl}. raven</b></div><div class="mini-meter"><i style="width:${100*(v-prev)/(next-prev)}%"></i></div></div>`}).join('');const q=quests[state.quest];ui.questTitle.textContent=q.title;ui.questText.textContent=q.text;ui.objectives.innerHTML=q.obj.map((o,i)=>`<div class="objective ${objectiveDone(i)?'done':''}">${o}</div>`).join('')}
  function objectiveDone(i){if(state.quest===1){if(i===0)return state.inventory.wood>=4;if(i===1)return state.inventory.mushroom>=3}return state.quest===5}
  function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;update(dt);draw();requestAnimationFrame(loop)}
  addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','e',' ','1'].includes(k))e.preventDefault();A.init();if(!e.repeat){if(k==='e')interact();if(k===' ')attack();if(k==='1')useMushroom()}keys[k]=true});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
  document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button,.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});
  document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.addEventListener('pointerdown',e=>{e.preventDefault();A.init();keys[k]=true});['pointerup','pointercancel','pointerleave'].forEach(ev=>b.addEventListener(ev,()=>keys[k]=false))});document.querySelector('[data-tap="interact"]').onclick=interact;document.querySelector('[data-tap="attack"]').onclick=attack;
  $('soundBtn').onclick=()=>{$('soundBtn').textContent=A.toggle()?'♫':'♩'};$('newBtn').onclick=()=>{if(confirm('Želiš izbrisati napredek in začeti novo zgodbo?')){localStorage.removeItem('mahInZerjavica');location.reload()}};$('wakeBtn').onclick=()=>{state.hp=state.maxHp;state.x=11*T;state.y=27*T;ui.death.classList.add('hidden');updateUI();save()};addEventListener('beforeunload',save);
  load();buildWorld();updateUI();setTimeout(()=>$('titleCard').remove(),5200);requestAnimationFrame(loop);
})();
