(function(){
'use strict';
const C=document.getElementById('game'),X=C.getContext('2d'),MC=document.getElementById('map'),MX=MC.getContext('2d');X.imageSmoothingEnabled=false;MX.imageSmoothingEnabled=false;
const W=C.width,H=C.height,T=32,WW=160,WH=96,A=window.GameAudio,$=id=>document.getElementById(id);
const ui={toast:$('toast'),prompt:$('prompt'),pin:$('pinText'),dialogue:$('dialogue'),speaker:$('speaker'),text:$('dialogueText'),portrait:$('portrait'),map:$('mapOverlay'),hp:$('hpBar'),hpText:$('hpText'),xp:$('xpBar'),xpText:$('xpText'),level:$('level'),coins:$('coins'),inventory:$('inventory'),detail:$('itemDetail'),skills:$('skillList'),qTitle:$('questTitle'),qText:$('questText'),objectives:$('objectives'),location:$('location'),compass:$('compass'),track:$('trackName'),death:$('death')};
const keys={},resources=[],enemies=[],particles=[],floaters=[],fireflies=[];let state,player,last=performance.now(),time=0,saveClock=0,camera={x:0,y:0},shake=0,dialogue=null,target=null,toastTimer,selectedItem=null,mapOpen=false,currentRegion='village';
const items={axe:{icon:'🪓',name:'Jelševa sekira',desc:'Dobro uravnotežena sekira. Z njo sekaj drevesa.',rare:1},sword:{icon:'⚔️',name:'Kratek meč',desc:'Zanesljiv meč za sluzavce, volkove in bojevite gobline.',rare:1},pick:{icon:'⛏️',name:'Rudarski kramp',desc:'Razbije tudi trdo modro skalo.',rare:1},wood:{icon:'▰',name:'Jelšev les',desc:'Dišeč, nekoliko vlažen les iz starega gozda.'},mushroom:{icon:'🍄',name:'Žerjavna goba',desc:'Povrne 35 življenja. Bližnjica: tipka 1.',use:true},berry:{icon:'●●',name:'Mrakova jagoda',desc:'Temno modra jagoda, s katero Mira barva tkanino.'},ore:{icon:'◆',name:'Modra ruda',desc:'Redka ruda iz vznožja Sivih zob.'},coin:{icon:'●',name:'Bakrenec',desc:'Svet se prepira, trgovci pa še vedno štejejo kovance.'},banner:{icon:'⚑',name:'Prazno goblinsko praporje',desc:'Dokaz, da nobena barva ni vredna vojne.',rare:1},scrap:{icon:'▧',name:'Goblinska zaponka',desc:'Kriva in cenena. Vendar Iva kupuje prav vse.'}};
const skillNames={woodcut:'Drvarjenje',forage:'Nabiralništvo',combat:'Bojevanje',mining:'Rudarjenje'};
const npcs=[{id:'mira',name:'Mira',x:15*T,y:49*T,body:'#735c8c',hair:'#d6c4a1'},{id:'iva',name:'Iva',x:22*T,y:53*T,body:'#456f78',hair:'#3a2b22'},{id:'grub',name:'General Grub',x:100*T,y:44*T,body:'#8d3e31',hair:'#3c3021',goblin:true},{id:'nib',name:'General Nib',x:119*T,y:57*T,body:'#435d8f',hair:'#30301f',goblin:true}];
const standard={x:109*T,y:49*T},camp={x:17*T,y:55*T},landmarks=[{name:'Jelševa vas',x:17,y:50,type:'town'},{name:'Rdeči tabor',x:100,y:44,type:'danger'},{name:'Modri tabor',x:119,y:57,type:'danger'},{name:'Ruševine kralja',x:130,y:15,type:'danger'},{name:'Sivi zobje',x:82,y:15,type:'town'}];
const rnd=(x,y,n=0)=>{const v=Math.sin(x*127.1+y*311.7+n*71.9)*43758.5453;return v-Math.floor(v)};
function riverCenter(ty){return 54+Math.sin(ty*.13)*5}
function waterTile(tx,ty){const river=Math.abs(tx-riverCenter(ty))<2.2&&!((ty>47&&ty<51)||(ty>72&&ty<76));const lake=tx>119&&tx<143&&ty>65&&ty<86&&Math.hypot((tx-131)/1.2,ty-76)<10;return tx<1||ty<1||tx>=WW-1||ty>=WH-1||river||lake}
function biomeAt(x,y){const tx=x/T,ty=y/T;if(tx>91&&tx<129&&ty>34&&ty<65)return'goblin';if(tx>62&&ty<30)return'mountain';if(tx>105&&ty>63)return'marsh';if(tx>121&&ty<31)return'ruins';if(Math.abs(tx-riverCenter(ty))<7)return'river';if(tx<34&&ty>39&&ty<66)return'village';return'forest'}
function pathTile(tx,ty){return(ty>=48&&ty<=50&&tx>5&&tx<111)||(tx>=99&&tx<=101&&ty>41&&ty<51)||(ty>=56&&ty<=58&&tx>99&&tx<123)||(tx>=108&&tx<=110&&ty>48&&ty<58)||(tx>=16&&tx<=18&&ty>48&&ty<58)}
function baseState(){return{x:17*T,y:57*T,hp:100,maxHp:100,xp:0,level:1,quest:0,inventory:{axe:1,sword:1,pick:1,wood:0,mushroom:1,berry:0,ore:0,coin:0,banner:0,scrap:0},skills:{woodcut:0,forage:0,combat:0,mining:0},harvested:{},bossDead:false,dir:-Math.PI/2,playtime:0}}
function load(){state=baseState();try{const s=JSON.parse(localStorage.getItem('mahInZerjavicaV2'));if(s&&s.inventory){state=Object.assign(state,s);state.inventory=Object.assign(baseState().inventory,s.inventory);state.skills=Object.assign(baseState().skills,s.skills)}}catch(e){}player={walk:0,attack:0,attackHit:false,invuln:0,action:null}}
function save(){state.playtime+=saveClock;saveClock=0;localStorage.setItem('mahInZerjavicaV2',JSON.stringify(state))}
function addResource(type,tx,ty,id){resources.push({type,x:tx*T,y:ty*T,id,hp:type==='tree'?3:type==='rock'?4:1,max:type==='tree'?3:type==='rock'?4:1,bump:0})}
function enemy(type,tx,ty,id){const stats={slime:[4,34],wolf:[6,62],goblin:[7,48],boss:[28,48]}[type];return{type,x:tx*T,y:ty*T,id,hp:stats[0],max:stats[0],speed:stats[1],dead:type==='boss'&&state.bossDead,hit:0,attack:0,phase:rnd(tx,ty)*6.28}}
function buildWorld(){
  for(let y=2;y<WH-2;y++)for(let x=2;x<WW-2;x++){if(waterTile(x,y)||pathTile(x,y)||(x>8&&x<28&&y>43&&y<61)||(x>94&&x<124&&y>39&&y<61)||(x>125&&x<138&&y>10&&y<22))continue;const b=biomeAt(x*T,y*T),r=rnd(x,y);if(b==='mountain'){if(r>.73)addResource('rock',x,y,'r'+x+'_'+y);else if(r>.68)addResource('tree',x,y,'t'+x+'_'+y)}else if(b==='marsh'){if(r>.9)addResource('tree',x,y,'t'+x+'_'+y);else if(r>.79&&r<.83)addResource('mushroom',x,y,'m'+x+'_'+y)}else{if(r>.88)addResource('tree',x,y,'t'+x+'_'+y);else if(r<.026)addResource('rock',x,y,'r'+x+'_'+y);else if(r>.80&&r<.825)addResource(rnd(x,y,7)>.5?'berry':'mushroom',x,y,'f'+x+'_'+y)}}
  [[35,43],[40,61],[65,68],[73,37],[87,32],[105,71],[115,77],[130,89]].forEach((p,i)=>addResource('berry',p[0],p[1],'berry'+i));[[72,22],[79,27],[87,18],[91,31],[68,15],[98,20]].forEach((p,i)=>addResource('rock',p[0],p[1],'ore'+i));
  [[31,55],[42,38],[65,58],[75,70],[86,43]].forEach((p,i)=>enemies.push(enemy('slime',p[0],p[1],'s'+i)));[[49,29],[70,40],[80,65],[93,27],[137,35]].forEach((p,i)=>enemies.push(enemy('wolf',p[0],p[1],'w'+i)));for(let i=0;i<18;i++)enemies.push(enemy('goblin',94+(i*7)%31,36+(i*11)%31,'g'+i));
  if(state.quest===6&&!state.bossDead)enemies.push(enemy('boss',111,48,'boglug'));
  for(let i=0;i<85;i++)fireflies.push({x:rnd(i,2)*WW*T,y:rnd(i,9)*WH*T,p:rnd(i,5)*6.28,s:7+rnd(i,8)*12});
}
function solidAt(x,y,r=10){if(waterTile(Math.floor(x/T),Math.floor(y/T)))return true;for(const n of npcs)if(Math.hypot(x-n.x,y-n.y)<r+14)return true;for(const o of resources)if(!state.harvested[o.id]&&o.type!=='mushroom'&&o.type!=='berry'&&Math.hypot(x-o.x,y-o.y)<r+14)return true;return false}
function notify(s){clearTimeout(toastTimer);ui.toast.textContent=s;ui.toast.classList.add('show');toastTimer=setTimeout(()=>ui.toast.classList.remove('show'),2200)}
function emit(x,y,color,n=9){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*110,vy:-25-Math.random()*90,life:.45+Math.random()*.55,color,size:2+Math.random()*3})}
function floatText(s,x,y,color='#f1d586'){floaters.push({s,x,y,color,life:1})}
function addItem(k,n=1){state.inventory[k]=(state.inventory[k]||0)+n;A.play('pickup');floatText('+'+n+' '+items[k].name,state.x,state.y-24);updateUI();save()}
function gain(skill,n){state.skills[skill]+=n;const old=state.level;state.xp+=n;state.level=1+Math.floor(Math.sqrt(state.xp/45));if(state.level>old){state.maxHp+=10;state.hp=state.maxHp;A.play('level');notify('Raven '+state.level+'! Moč v tebi raste.')}updateUI()}
function useMushroom(){if(!state.inventory.mushroom||state.hp>=state.maxHp)return;state.inventory.mushroom--;state.hp=Math.min(state.maxHp,state.hp+35);A.play('heal');emit(state.x,state.y,'#9fd46b',15);notify('Žerjavna toplota zaceli rane.');updateUI();save()}
function speak(name,lines,end){dialogue={name,lines,i:0,end};showLine()}
function showLine(){ui.speaker.textContent=dialogue.name;ui.portrait.textContent=dialogue.name[0];ui.text.textContent=dialogue.lines[dialogue.i];ui.dialogue.classList.remove('hidden');A.play('talk')}
function nextLine(){if(!dialogue)return;dialogue.i++;if(dialogue.i>=dialogue.lines.length){ui.dialogue.classList.add('hidden');const fn=dialogue.end;dialogue=null;if(fn)fn()}else showLine()}
function talkMira(){
  if(state.quest===0)speak('Mira',['Arin, ravno prav. Goblini z vzhoda so spet na bojni nogi. Tokrat zaradi barve zastave.','Rdečekape pravijo, da je rdeča pogumna. Modri škornji trdijo, da je modra pametna. Oboji so oboroženi in nihče ni ne eno ne drugo.','Poišči generala Gruba v Rdečem taboru onkraj reke. Poskusi izvedeti, kaj bi ga spravilo za isto mizo z generalom Nibom.'],()=>setQuest(1,'Nova naloga: Tri barve prepira'));
  else if(state.quest<4)speak('Mira',['Sledi vzhodni poti čez kamniti most. Na razpotju bodo njihove grde zastave pokazale smer.']);
  else if(state.quest===4)speak('Mira',['Mrakove jagode za modro, modra ruda za sijaj ... in malo pepela, da užaliva obe strani enako.','Tukaj je prazno praporje. Odnesi ga na Zborni kol v središču obeh taborov. Če vprašajo, je barva »dostojanstveno blatna«.'],()=>{state.inventory.berry-=5;state.inventory.ore-=3;state.inventory.banner=1;setQuest(5,'Prejel si nevtralno praporje.');A.play('quest')});
  else if(state.quest===7)speak('Mira',['Torej je Boglug pojedel zastavo in nato še skoraj tebe? To je nenavadno dober diplomatski izid.','Brez simbola se goblini nimajo za kaj prepirati. Dolina ima mir — vsaj do naslednje barve.'],()=>{state.inventory.coin+=80;setQuest(8,'Naloga opravljena · +80 bakrencev');A.play('quest')});
  else if(state.quest===8)speak('Mira',['Kadar diplomacija odpove, očitno potrebujemo več blata.']);else speak('Mira',['Ne dovoli, da te njihovi nazivi prestrašijo. Vsak tretji goblin je general.']);
}
function talkGrub(){if(state.quest===1)speak('General Grub',['Stoj! Jaz General Grub, devetnajsti svojega imena! Rdeča najboljša barva. Tudi kri rdeča. Tudi juha, ko kuhar zameša lonec.','Nib pravi modra boljša. Pojdi k njemu. Povej mu Grub sprejme samo barvo, ki je boljša od obeh!'],()=>setQuest(2,'Poišči generala Niba v Modrem taboru.'));else if(state.quest>=5)speak('General Grub',['Blatna zastava grda. To pomeni poštena. Grub skoraj zadovoljen.']);else speak('General Grub',['Nib živi jugovzhodno. Sledi modrim cunjam in vonju slabe juhe.'])}
function talkNib(){if(state.quest===2)speak('General Nib',['Grub je bedak. Rdeča privabi bike in davkarje. Modra je barva strategije!','Toda barva boljša od obeh? Hm. Vaša Mira pozna barvila. Prinesi ji pet mrakovih jagod in tri kose modre rude. Naj naredi barvo, ki je nihče ne more zahtevati zase.'],()=>setQuest(3,'Zberi sestavine za nevtralno barvo.'));else speak('General Nib',['Ruda je v gorah severno od reke. Jagode rastejo ob poteh in v močvirju.'])}
function talkIva(){speak('Iva',['Zemljevid odpreš s tipko M. Rumeni diamant vedno pokaže naslednji cilj.','Če se izgubiš: reka deli dolino, dva kamnita mostova pa jo spet sestavita.'])}
function setQuest(q,msg){state.quest=q;A.play('quest');if(msg)notify(msg);updateUI();save()}
function activateStandard(){if(state.quest!==5){notify('Na kolu visijo ostanki številnih slabih odločitev.');return}state.inventory.banner=0;setQuest(6,'Nekaj velikega prihaja iz grmovja ...');shake=14;emit(standard.x,standard.y,'#e5b654',35);const b=enemy('boss',111,48,'boglug');enemies.push(b);speak('Boglug, jedec praporov',['BLOP! Nova zastava! Boglug poje barve. Potem poje diplomata.'])}
function beginAction(o){if(player.action||player.attack)return;const type=o.type==='tree'?'chop':o.type==='rock'?'mine':'pick';player.action={type,o,t:0,hit:false,total:type==='pick'?.42:.68};state.dir=Math.atan2(o.y-state.y,o.x-state.x)}
function applyAction(a){const o=a.o;if(state.harvested[o.id])return;if(o.type==='tree'||o.type==='rock'){o.hp--;o.bump=1;A.play(o.type==='tree'?'chop':'mine');emit(o.x,o.y,o.type==='tree'?'#a77a43':'#9cabad',9);if(o.hp<=0){state.harvested[o.id]=true;addItem(o.type==='tree'?'wood':'ore');gain(o.type==='tree'?'woodcut':'mining',o.type==='tree'?7:9)}}else{state.harvested[o.id]=true;addItem(o.type);gain('forage',6)}if(state.quest===3&&state.inventory.berry>=5&&state.inventory.ore>=3)setQuest(4,'Sestavine zbrane. Vrni se k Miri.');updateUI()}
function interact(){A.init();if(dialogue){nextLine();return}if(mapOpen){toggleMap();return}if(!target)return;const a=target;if(a.kind==='npc'){({mira:talkMira,iva:talkIva,grub:talkGrub,nib:talkNib}[a.o.id])();return}if(a.kind==='standard'){activateStandard();return}beginAction(a.o)}
function attack(){A.init();if(dialogue||mapOpen||player.action||player.attack)return;player.attack=.42;player.attackHit=false;A.play('sword')}
function attackHit(){for(const e of enemies){if(e.dead)continue;const d=Math.hypot(e.x-state.x,e.y-state.y),ang=Math.atan2(e.y-state.y,e.x-state.x),delta=Math.atan2(Math.sin(ang-state.dir),Math.cos(ang-state.dir));if(d<57&&Math.abs(delta)<1.2){const dmg=2+Math.floor(state.level/3);e.hp-=dmg;e.hit=.24;shake=4;floatText('-'+dmg,e.x,e.y-25,'#ffdc91');emit(e.x,e.y,e.type==='goblin'||e.type==='boss'?'#79954f':'#85b797',9);if(e.hp<=0)kill(e)}}}
function kill(e){e.dead=true;gain('combat',e.type==='boss'?55:e.type==='goblin'?12:e.type==='wolf'?10:7);addItem(e.type==='goblin'||e.type==='boss'?'scrap':'coin',e.type==='boss'?5:1);if(e.type==='boss'){state.bossDead=true;setQuest(7,'Boglug je premagan. Vrni se k Miri.');A.play('quest');emit(e.x,e.y,'#edc568',45)}}
function hurt(n){if(player.invuln||state.hp<=0)return;state.hp-=n;player.invuln=.85;shake=8;A.play('hurt');floatText('-'+n,state.x,state.y-28,'#ff8478');if(state.hp<=0){state.hp=0;ui.death.classList.remove('hidden')}updateUI()}
function updatePlayer(dt){if(player.action){player.action.t+=dt;if(!player.action.hit&&player.action.t/player.action.total>.48){player.action.hit=true;applyAction(player.action)}if(player.action.t>=player.action.total)player.action=null}if(player.attack){player.attack=Math.max(0,player.attack-dt);if(!player.attackHit&&player.attack<.23){player.attackHit=true;attackHit()}}let dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);const l=Math.hypot(dx,dy)||1;dx/=l;dy/=l;const locked=dialogue||mapOpen||player.action,speed=locked?0:145;if(dx||dy)state.dir=Math.atan2(dy,dx);const nx=state.x+dx*speed*dt,ny=state.y+dy*speed*dt;if(!solidAt(nx,state.y))state.x=nx;if(!solidAt(state.x,ny))state.y=ny;if(speed&&(dx||dy)){player.walk+=dt*10;if(Math.floor(player.walk*1.8)%8===0&&Math.floor((player.walk-dt*10)*1.8)%8!==0)A.play('step')}player.invuln=Math.max(0,player.invuln-dt);state.x=Math.max(T,Math.min((WW-1)*T,state.x));state.y=Math.max(T,Math.min((WH-1)*T,state.y))}
function updateEnemies(dt){for(const e of enemies){if(e.dead)continue;e.hit=Math.max(0,e.hit-dt);e.attack=Math.max(0,e.attack-dt);const d=Math.hypot(state.x-e.x,state.y-e.y);if(d<250&&!dialogue&&!mapOpen){const a=Math.atan2(state.y-e.y,state.x-e.x)+Math.sin(time*1.7+e.phase)*.25;e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt;if(d<30&&e.attack<=0){e.attack=1.15;if(e.type==='goblin'||e.type==='boss')A.play('goblin');hurt(e.type==='boss'?17:e.type==='goblin'?9:e.type==='wolf'?11:7)}}}}
function nearest(){let b=null,d=55;for(const n of npcs){const q=Math.hypot(n.x-state.x,n.y-state.y);if(q<d){d=q;b={kind:'npc',o:n,label:'Govori z '+n.name}}}for(const o of resources){if(state.harvested[o.id])continue;const q=Math.hypot(o.x-state.x,o.y-state.y);if(q<d){d=q;b={kind:'resource',o,label:o.type==='tree'?'Posekaj drevo':o.type==='rock'?'Izkoplji modro rudo':o.type==='berry'?'Naberi mrakove jagode':'Naberi žerjavno gobo'}}}const ds=Math.hypot(standard.x-state.x,standard.y-state.y);if(ds<d)b={kind:'standard',label:'Uporabi Zborni kol'};target=b;ui.prompt.classList.toggle('show',!!b&&!dialogue&&!mapOpen);ui.prompt.innerHTML=b?'<b>E</b> · '+b.label:''}
function updateFx(dt){for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=120*dt;p.life-=dt}for(const f of floaters){f.y-=28*dt;f.life-=dt}for(let i=particles.length-1;i>=0;i--)if(particles[i].life<=0)particles.splice(i,1);for(let i=floaters.length-1;i>=0;i--)if(floaters[i].life<=0)floaters.splice(i,1);for(const o of resources)o.bump=Math.max(0,o.bump-dt*5)}
function questTarget(){switch(state.quest){case 0:return{x:npcs[0].x,y:npcs[0].y,label:'Pogovori se z Miro'};case 1:return{x:npcs[2].x,y:npcs[2].y,label:'Poišči generala Gruba'};case 2:return{x:npcs[3].x,y:npcs[3].y,label:'Poišči generala Niba'};case 3:return{x:78*T,y:24*T,label:'Zberi 5 jagod in 3 rude'};case 4:return{x:npcs[0].x,y:npcs[0].y,label:'Vrni se k Miri'};case 5:return{x:standard.x,y:standard.y,label:'Obesi nevtralno praporje'};case 6:return{x:111*T,y:48*T,label:'Premagaj Bogluga'};case 7:return{x:npcs[0].x,y:npcs[0].y,label:'Poročaј Miri'};default:return{x:130*T,y:15*T,label:'Razišči dolino'}}}
function update(dt){if(state.hp>0){updatePlayer(dt);updateEnemies(dt);nearest()}updateFx(dt);time+=dt;saveClock+=dt;if(saveClock>9)save();camera.x+=(state.x-W/2-camera.x)*Math.min(1,dt*5);camera.y+=(state.y-H/2-camera.y)*Math.min(1,dt*5);camera.x=Math.max(0,Math.min(WW*T-W,camera.x));camera.y=Math.max(0,Math.min(WH*T-H,camera.y));shake=Math.max(0,shake-dt*25);const r=biomeAt(state.x,state.y);if(r!==currentRegion){currentRegion=r;ui.track.textContent=A.setRegion(r)}ui.location.textContent=regionName(r);const g=questTarget(),dist=Math.round(Math.hypot(g.x-state.x,g.y-state.y)/T);ui.pin.textContent=g.label;ui.compass.textContent='Cilj: '+g.label+' · '+dist+' korakov'}
function regionName(r){return{village:'Jelševa vas',forest:'Veliki zeleni gozd',river:'Reka Šepetalka',mountain:'Sivi zobje',marsh:'Močvirje kresnic',goblin:'Goblinska meja',ruins:'Ruševine starega kralja'}[r]}
const sx=x=>Math.round(x-camera.x),sy=y=>Math.round(y-camera.y);
function tile(tx,ty){const x=tx*T-camera.x,y=ty*T-camera.y,b=biomeAt(tx*T,ty*T);if(waterTile(tx,ty)){X.fillStyle='#294c52';X.fillRect(x,y,T+1,T+1);X.fillStyle='#83b4aa44';const w=(time*15+tx*8+ty*4)%27;X.fillRect(x+w-8,y+9,10,2);X.fillRect(x+25-w/2,y+23,8,1);return}if(pathTile(tx,ty))X.fillStyle=(tx+ty)%2?'#766f51':'#6f684c';else{const palettes={village:['#4e7545','#557d49','#496f42'],forest:['#315a36','#39623a','#3e6840'],river:['#426f47','#47754a','#3d6942'],mountain:['#596257','#626a5e','#4e594f'],marsh:['#344f3c','#3b5941','#2e4938'],goblin:['#5c633a','#656a3d','#515a36'],ruins:['#4b5748','#535e50','#414c40']},p=palettes[b],n=rnd(tx,ty);X.fillStyle=p[n>.66?0:n>.33?1:2]}X.fillRect(x,y,T+1,T+1);if(!pathTile(tx,ty)&&rnd(tx,ty,2)>.74){X.fillStyle=b==='mountain'?'#7a8275':'#729257';X.fillRect(x+5+rnd(tx,ty,3)*20,y+6+rnd(tx,ty,4)*18,2,4)}}
function shadow(x,y,w=22){X.fillStyle='#07100744';X.beginPath();X.ellipse(sx(x),sy(y)+12,w,7,0,0,7);X.fill()}
function tree(o){const x=sx(o.x),y=sy(o.y),s=Math.sin(time*1.1+o.x*.01)*1.7+o.bump*4;shadow(o.x,o.y,22);X.fillStyle='#604329';X.fillRect(x-4,y-4,8,27);X.fillStyle='#1f4329';X.beginPath();X.arc(x+s-9,y-14,16,0,7);X.arc(x+s+9,y-17,18,0,7);X.arc(x+s,y-30,17,0,7);X.fill();X.fillStyle='#487641';X.fillRect(x+s-8,y-32,8,5);X.fillRect(x+s+10,y-20,7,4)}
function rock(o){const x=sx(o.x),y=sy(o.y);shadow(o.x,o.y,17);X.fillStyle='#626d6c';X.beginPath();X.moveTo(x-18,y+13);X.lineTo(x-14,y-9);X.lineTo(x+2,y-18);X.lineTo(x+18,y-3);X.lineTo(x+14,y+14);X.fill();X.fillStyle='#a7b1ac';X.fillRect(x-8,y-9,11,3);X.fillStyle='#5fa0ac';X.fillRect(x+4,y-5,5,9)}
function forage(o){const x=sx(o.x),y=sy(o.y);if(o.type==='berry'){X.fillStyle='#2a5735';X.fillRect(x-9,y,18,11);X.fillStyle='#6658ad';X.fillRect(x-7,y-4,5,5);X.fillRect(x+2,y-7,5,5);X.fillRect(x+6,y+1,4,4)}else{X.fillStyle='#dfd1a5';X.fillRect(x-2,y,4,9);X.fillStyle='#c45b45';X.beginPath();X.arc(x,y,7+Math.sin(time*2+o.x)*.5,Math.PI,Math.PI*2);X.fill();X.fillStyle='#f2bd76';X.fillRect(x-3,y-5,2,2)}}
function person(x,y,body,hair,walk=0,dir=0,goblin=false,anim=null){const px=sx(x),py=sy(y),bob=Math.abs(Math.sin(walk))*(-2);shadow(x,y,goblin?13:12);X.save();X.translate(px,py+bob);const skin=goblin?'#78944d':'#c99769';X.fillStyle='#242019';X.fillRect(-8,10+(Math.sin(walk)>0?2:0),6,11);X.fillRect(2,10+(Math.sin(walk)<0?2:0),6,11);X.fillStyle=body;X.fillRect(-10,-7,20,20);X.fillStyle=skin;X.fillRect(-7,-18,goblin?15:14,12);if(goblin){X.fillRect(-12,-14,6,4);X.fillRect(7,-14,6,4)}X.fillStyle=hair;X.fillRect(-8,-21,16,6);X.fillStyle='#191b14';X.fillRect(Math.cos(dir)>0?2:-4,-14,2,2);const armSwing=Math.sin(walk)*5;X.strokeStyle=skin;X.lineWidth=5;X.beginPath();X.moveTo(-8,-4);X.lineTo(-12+Math.cos(dir)*armSwing,6);X.moveTo(8,-4);X.lineTo(12-Math.cos(dir)*armSwing,6);X.stroke();if(anim)drawTool(anim,dir);X.restore()}
function drawTool(anim,dir){let progress=anim.progress||0,angle=dir;if(anim.type==='attack')angle=dir-1.45+progress*2.7;else angle=dir-1.7+Math.sin(progress*Math.PI)*2.2;X.rotate(angle);X.translate(0,-1);X.strokeStyle='#c3aa73';X.lineWidth=3;X.beginPath();X.moveTo(7,0);X.lineTo(27,0);X.stroke();if(anim.type==='chop'){X.fillStyle='#aeb7b1';X.fillRect(24,-7,8,14)}else if(anim.type==='mine'){X.strokeStyle='#abb5b1';X.lineWidth=4;X.beginPath();X.moveTo(23,-8);X.lineTo(31,0);X.lineTo(23,8);X.stroke()}else{X.strokeStyle='#e6dfc3';X.lineWidth=4;X.beginPath();X.moveTo(24,0);X.lineTo(38,0);X.stroke();X.fillStyle='#e6dfc3';X.beginPath();X.moveTo(40,0);X.lineTo(34,-4);X.lineTo(34,4);X.fill()}}
function goblinEnemy(e){const p=e.attack>.75?{type:'attack',progress:(1.15-e.attack)/.4}:null;person(e.x,e.y,e.type==='boss'?'#6b4130':'#665638','#302a1d',time*5+e.phase,Math.atan2(state.y-e.y,state.x-e.x),true,p);const x=sx(e.x),y=sy(e.y);if(e.type==='boss'){X.fillStyle='#a9513c';X.fillRect(x-18,y-27,36,6)}if(e.hp<e.max){X.fillStyle='#151915';X.fillRect(x-18,y-32,36,4);X.fillStyle='#c3594f';X.fillRect(x-18,y-32,36*e.hp/e.max,4)}}
function creature(e){if(e.type==='goblin'||e.type==='boss'){goblinEnemy(e);return}const x=sx(e.x),y=sy(e.y),p=Math.sin(time*4+e.phase);shadow(e.x,e.y,14);X.save();if(e.hit)X.globalAlpha=.55;if(e.type==='slime'){X.fillStyle='#6fa24b';X.beginPath();X.ellipse(x,y+3,16+p,13-p*.5,0,Math.PI,0);X.lineTo(x+16,y+11);X.lineTo(x-16,y+11);X.fill();X.fillStyle='#172014';X.fillRect(x-7,y,3,3);X.fillRect(x+5,y,3,3)}else{X.fillStyle='#555f55';X.fillRect(x-14,y-7,27,16);X.fillStyle='#737d6f';X.fillRect(x+8,y-12,14,12);X.fillStyle='#d1c090';X.fillRect(x+18,y-10,2,2);X.fillStyle='#343a33';X.fillRect(x-12,y+8,5,9);X.fillRect(x+6,y+8,5,9)}X.restore();if(e.hp<e.max){X.fillStyle='#171b17';X.fillRect(x-17,y-25,34,4);X.fillStyle='#c45b4f';X.fillRect(x-17,y-25,34*e.hp/e.max,4)}}
function house(tx,ty,roof='#3e3022'){const x=sx(tx*T),y=sy(ty*T);X.fillStyle='#725a39';X.fillRect(x-45,y-35,90,55);X.fillStyle=roof;X.beginPath();X.moveTo(x-54,y-34);X.lineTo(x,y-70);X.lineTo(x+54,y-34);X.fill();X.fillStyle='#d0a258';X.fillRect(x-7,y-5,14,25);X.fillStyle='#96b08a';X.fillRect(x-32,y-22,15,13)}
function props(){house(13,47);house(23,48,'#443326');house(18,57,'#34412b');for(const c of [[96,42,'#913c31'],[103,40,'#913c31'],[115,55,'#405c8d'],[122,53,'#405c8d']]){const x=sx(c[0]*T),y=sy(c[1]*T);X.fillStyle='#6b4930';X.beginPath();X.moveTo(x-18,y+15);X.lineTo(x,y-18);X.lineTo(x+18,y+15);X.fill();X.strokeStyle=c[2];X.lineWidth=4;X.stroke()}const x=sx(standard.x),y=sy(standard.y);X.fillStyle='#5f452a';X.fillRect(x-3,y-25,6,43);X.fillStyle=state.quest===5?'#b9ac7d':'#6d5a3d';X.fillRect(x+3,y-22,25,15)}
function drawWorld(){const jx=shake?(Math.random()-.5)*shake:0,jy=shake?(Math.random()-.5)*shake:0;X.clearRect(0,0,W,H);X.save();X.translate(jx,jy);for(let y=Math.floor(camera.y/T);y<=Math.ceil((camera.y+H)/T);y++)for(let x=Math.floor(camera.x/T);x<=Math.ceil((camera.x+W)/T);x++)tile(x,y);props();const list=[];for(const o of resources)if(!state.harvested[o.id])list.push({y:o.y,fn:()=>o.type==='tree'?tree(o):o.type==='rock'?rock(o):forage(o)});for(const n of npcs)list.push({y:n.y,fn:()=>{person(n.x,n.y,n.body,n.hair,0,0,n.goblin);X.fillStyle='#f0dfad';X.font='11px Georgia';X.textAlign='center';X.fillText(n.name,sx(n.x),sy(n.y)-29)}});for(const e of enemies)if(!e.dead)list.push({y:e.y,fn:()=>creature(e)});list.push({y:state.y,fn:()=>{if(player.invuln&&Math.floor(player.invuln*12)%2)return;let anim=null;if(player.action)anim={type:player.action.type,progress:player.action.t/player.action.total};else if(player.attack)anim={type:'attack',progress:1-player.attack/.42};person(state.x,state.y,'#496b8f','#4b3428',player.walk,state.dir,false,anim)}});list.sort((a,b)=>a.y-b.y).forEach(v=>v.fn());
  const g=questTarget(),gx=sx(g.x),gy=sy(g.y);if(gx>10&&gx<W-10&&gy>10&&gy<H-10){X.fillStyle='#e7c351';X.beginPath();X.moveTo(gx,gy-35+Math.sin(time*4)*3);X.lineTo(gx-6,gy-45+Math.sin(time*4)*3);X.lineTo(gx+6,gy-45+Math.sin(time*4)*3);X.fill()}
  for(const f of fireflies){const a=.2+.6*(Math.sin(time*2+f.p)*.5+.5),x=sx(f.x+Math.sin(time+f.p)*f.s),y=sy(f.y+Math.cos(time*.8+f.p)*f.s);if(x>0&&x<W&&y>0&&y<H){X.fillStyle=`rgba(239,211,105,${a})`;X.fillRect(x,y,2,2)}}for(const p of particles){X.globalAlpha=Math.max(0,p.life);X.fillStyle=p.color;X.fillRect(sx(p.x),sy(p.y),p.size,p.size)}X.globalAlpha=1;for(const f of floaters){X.globalAlpha=Math.max(0,f.life);X.fillStyle=f.color;X.font='bold 12px Georgia';X.textAlign='center';X.fillText(f.s,sx(f.x),sy(f.y))}X.globalAlpha=1;X.restore()}
const quests={0:['Tri barve prepira','V Jelševi vasi te išče starešina Mira.',['Pogovori se z Miro']],1:['Čez reko','Mira želi ustaviti goblinski spor, preden doseže vas.',['Prečkaj reko po kamnitem mostu','Poišči Rdeči tabor','Govori z generalom Grubom']],2:['Drugo mnenje','Grub zahteva barvo, boljšo od rdeče in modre.',['Poišči Modri tabor','Govori z generalom Nibom']],3:['Barva nikogar','Mira potrebuje naravna barvila in mineralni sijaj.',['Zberi 5 mrakovih jagod','Izkoplji 3 kose modre rude']],4:['Barva nikogar','Vse sestavine so zbrane.',['Vrni se k Miri v Jelševo vas']],5:['Zborni kol','Nevtralno praporje mora viseti med obema taboroma.',['Poišči Zborni kol','Obesi praporje']],6:['Jedec barv','Praporje je privabilo lačnega Bogluga.',['Premagaj Bogluga, jedca praporov']],7:['Mir po goblinsko','Prepir je končan na zelo nenavaden način.',['Vrni se k Miri']],8:['Tri barve prepira','Goblini so začasno pozabili, zakaj so bili jezni.',['Naloga opravljena']]};
function objectiveDone(i){if(state.quest===3)return i===0?state.inventory.berry>=5:state.inventory.ore>=3;return state.quest===8}
function updateUI(){ui.hp.style.width=100*state.hp/state.maxHp+'%';ui.hpText.value=Math.ceil(state.hp)+' / '+state.maxHp;const prev=45*(state.level-1)*(state.level-1),next=45*state.level*state.level;ui.xp.style.width=100*(state.xp-prev)/(next-prev)+'%';ui.xpText.value=state.xp+' / '+next;ui.level.textContent=state.level;ui.coins.textContent='● '+state.inventory.coin;const keys=Object.keys(items).filter(k=>(state.inventory[k]||0)>0),slots=20;ui.inventory.innerHTML=Array.from({length:slots},(_,i)=>{const k=keys[i];if(!k)return'<div class="slot"></div>';const d=items[k],n=state.inventory[k]||0;return`<button class="slot ${selectedItem===k?'selected':''}" data-item="${k}" aria-label="${d.name}: ${n}">${d.icon}${n>1?`<small>${n}</small>`:''}${d.rare?'<i class="rare"></i>':''}</button>`}).join('');ui.inventory.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>selectItem(b.dataset.item));ui.skills.innerHTML=Object.entries(state.skills).map(([k,v])=>{const l=1+Math.floor(Math.sqrt(v/25)),a=25*(l-1)*(l-1),z=25*l*l;return`<div class="skill-row"><div><span>${skillNames[k]}</span><b>${l}. raven</b></div><div class="mini-meter"><i style="width:${100*(v-a)/(z-a)}%"></i></div></div>`}).join('');const q=quests[state.quest],objectives=state.quest===3?[`Zberi 5 mrakovih jagod (${Math.min(5,state.inventory.berry)}/5)`,`Izkoplji 3 kose modre rude (${Math.min(3,state.inventory.ore)}/3)`]:q[2];ui.qTitle.textContent=q[0];ui.qText.textContent=q[1];ui.objectives.innerHTML=objectives.map((o,i)=>`<div class="objective ${objectiveDone(i)?'done':(!objectiveDone(0)&&i===0)||(objectiveDone(0)&&i===1)?'active':''}">${o}</div>`).join('');if(selectedItem&&state.inventory[selectedItem])selectItem(selectedItem,true)}
function selectItem(k,quiet=false){selectedItem=k;const d=items[k],n=state.inventory[k]||0;ui.detail.innerHTML=`${d.use&&n?'<button id="useItem">Uporabi</button>':''}<span>${d.name} · ${n}</span><small>${d.desc}</small>`;if(d.use&&n)$('useItem').onclick=useMushroom;if(!quiet)updateUI()}
function drawMap(){const w=MC.width,h=MC.height,sx=w/WW,sy=h/WH;MX.fillStyle='#b7a674';MX.fillRect(0,0,w,h);for(let y=0;y<WH;y+=2)for(let x=0;x<WW;x+=2){const b=biomeAt(x*T,y*T);MX.fillStyle=waterTile(x,y)?'#527b78':b==='mountain'?'#777a6c':b==='marsh'?'#53664d':b==='goblin'?'#777245':b==='ruins'?'#5f6656':'#617b4f';MX.fillRect(x*sx,y*sy,2*sx+1,2*sy+1)}MX.strokeStyle='#8b7652';MX.lineWidth=2;MX.beginPath();for(let x=5;x<111;x++){const px=x*sx,py=49*sy;x===5?MX.moveTo(px,py):MX.lineTo(px,py)}MX.stroke();for(const l of landmarks){MX.fillStyle=l.type==='danger'?'#923e38':'#754c31';MX.fillRect(l.x*sx-3,l.y*sy-3,7,7);MX.fillStyle='#302a22';MX.font='10px Georgia';MX.fillText(l.name,l.x*sx+6,l.y*sy+3)}const g=questTarget();MX.fillStyle='#e4bd52';MX.beginPath();MX.arc(g.x/T*sx,g.y/T*sy,6+Math.sin(time*4),0,7);MX.fill();MX.fillStyle='#f5f0dd';MX.beginPath();MX.arc(state.x/T*sx,state.y/T*sy,5,0,7);MX.fill()}
function toggleMap(){mapOpen=!mapOpen;ui.map.classList.toggle('hidden',!mapOpen);A.play('ui');if(mapOpen)drawMap()}
function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;update(dt);drawWorld();if(mapOpen)drawMap();requestAnimationFrame(loop)}
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','e',' ','1','m'].includes(k))e.preventDefault();A.init();if(!e.repeat){if(k==='e')interact();if(k===' ')attack();if(k==='1')useMushroom();if(k==='m')toggleMap()}keys[k]=true});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button,.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active');A.play('ui')});document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.onpointerdown=e=>{e.preventDefault();A.init();keys[k]=true};b.onpointerup=b.onpointercancel=b.onpointerleave=()=>keys[k]=false});document.querySelector('[data-tap="interact"]').onclick=interact;document.querySelector('[data-tap="attack"]').onclick=attack;$('mapBtn').onclick=$('closeMap').onclick=toggleMap;$('soundBtn').onclick=()=>{$('soundBtn').textContent=A.toggle()?'♫':'♩'};$('newBtn').onclick=()=>{if(confirm('Izbrišem napredek in začnem novo zgodbo?')){localStorage.removeItem('mahInZerjavicaV2');location.reload()}};$('wakeBtn').onclick=()=>{state.hp=state.maxHp;state.x=camp.x;state.y=camp.y;ui.death.classList.add('hidden');updateUI();save()};addEventListener('beforeunload',save);
load();buildWorld();updateUI();ui.track.textContent=A.trackName();setTimeout(()=>{const t=$('titleCard');if(t)t.remove()},6200);requestAnimationFrame(loop);
})();
